### ISSUE TITLE
Search on all versions not working, selecting Yes always slides to No before search

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1044]
Seems like this is the opposite of #115.  See below:

![search-all-versions-fail](https://cloud.githubusercontent.com/assets/1377228/13883291/c507ebcc-ecf6-11e5-881b-0a6eb9c53596.gif)

Note - this is not possible on Alfresco since searching on the version store isn't a thing in Alfresco.

**Comment by vachanta93** [comment]
Fixed with Rev #14622.

Fix was to add an OR statement in `validateParamAgainstForm` to keep the `searchallversions` parameter on the `searchParameters` in the `query` so the slider doesn't change back to No after the search finished running.

Also moved the `search:execute` and `search:result:controls:numResults` listeners from afterRender to initialize and moved the `search:execute` functionality into its own method called `executeSearch`.

CR - Blum
