### ISSUE TITLE
Recent Folders No longer Works with latest Admin Toss Across

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1052]
The recent folders config on release2 looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/14001461/fa16139a-f113-11e5-9999-c88c3a72aa39.png)

If you try to fix the config and save, recent objects no longer displays anything:

![image](https://cloud.githubusercontent.com/assets/1377228/14001481/12644c96-f114-11e5-85a5-9c53f1d69df0.png)

I'm guessing this is related to the fix for #590, but just a guess

**Comment by nquillin91** [comment]
Modified recentobjects.js and recentobjectsdashletconfig.js

In recentobjectsdashletconfig.js in the function buildAttrsTossAcross the 'selectedAttributes' was getting set to self.targetCollection which has been changed so that it is now set to a mappedTargetCollection (array instead of backbone collection). This was necessary because originally after saving a change to the recent objects dashlet the 'selectedAttributes' would be stored as a backbone collection but upon retrieving all the data again due to a refresh or page navigation after the initial pull the backbone collection gets converted to an array. This caused a problem with grabbing ocNames because the objectType was changing between backbone collection and array. This change will keep the 'selectedAttributes' as an array preventing the need for any messy code fixes later down the line.

In recentobjects.js after ocNames has been retrieved via self.config.get. The ocNames are plucked from the array. (change was needed because originally this wasn't returning an object).

Also in recentobjects.js in ocoSuccessCall the _.each has had index added to keep track of where the data should be placed. This matters when there is a date detected. Originally the date was being placed incorrectly because the set was occurring via a constant and not dynamically. 

ie tempRecentObject.properties[1] vs tempRecentObject.properties[index]

Fixed with revision: 14734

CR- Bradley White
