### ISSUE TITLE
Auto-launched actions show up small with scrollbar

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1059]
Something must have changed in the stage recently.  When I load an insurance folder on edge2, the view all docs action shows up with a scrollbar and the view pane is really small:

![image](https://cloud.githubusercontent.com/assets/1377228/14356719/9bd17c9a-fcab-11e5-92ca-1247d60f08bb.png)

If I click the action to load it again, the screen looks fine:

![image](https://cloud.githubusercontent.com/assets/1377228/14356708/8f6aa3be-fcab-11e5-9642-aadf1efc7082.png)

@devinjackson is going to look into this as part of the "stage double scrollbar" enhancement

**Comment by devinjackson** [comment]
Added a call to resizeRightSideActionHandler at the end of windowResizePanes, which is called on the initial load of the stage.  Now the right side action handler will reach the expected size on initial load and it will resize when the window is resized as well. If the height of the right side action handler exceeds the height of the window, then a custom scroll bar will appear for the user.

Fixed with HPI revision 14983.

CR - Marc
