### ISSUE TITLE
Ability to Configure Aspects in HPI

### ISSUE THREAD

**Issue by maxwellmstein** [tsgrp/HPI#109]
We currently do not support aspect properites, as of last discussion here was the plan:

In the OTC config, you would select a type. Then from the section where you can add properties, set the label etc. There would be a button to 'Add available aspects'. Clicking on that would bring up a list of aspects OC knows about. Selecting an aspect would find all the aspects properties and add them to the props list. (See the code for add property) It should provide a pretty solid sample of a custom modal and adding HPItypeattr config entries)

I don't think we need the ability to 'remove' aspect or even track which aspects are on. If you want to remove, you can just delete all the properties of that aspect from the config.

The downside of this approach is that we'd potentially need to add aspects like titleable and lockable to every type. Ideally there would be a separate aspect config, the issue is that any code that currently leverages the OTC (a lot) would potentially need to cross reference against every configured aspect....Long story short there I think this approach would lead us to a ton of convuluted code that is slow. I think the first solution I listed is much better. If configuring aspects is painful, I think our time would be better spent creating a 'add aspect to all types ' sort of button.

**Comment by gsteimer** [comment]
Updating this issue since now HPI has the "One OTC to rule them all" and Form Config, which change the way we could do non-mandatory Aspects in HPI.

I don't think we need to create add/remove aspect actions in HPI at this point.  Simply being able to handle non-mandatory aspects in Alfresco would be nice.  Here's one way we could do it:

**OC Updates**
* Update the dictionary service to read in non-mandatory aspects.
* New method - `IContent#hasAspect(String ticket, String objectId, String aspectOcName)`

**HPI Updates**
* Create a new config in the admin - Aspect Type Config (ATC?).  This would mirror the OTC, but you'd only be able to configure non-mandatory aspects and the associated attributes.
* In form config, add the ability to add an 'aspect section' to the form.  Then, within the aspect, allow the admin to configure the attributes, just like normal type attributes (control type, required, etc).
* When displaying the form, if it runs into an aspect section, check to see if the document has that aspect (using the `hasAspect` OC method from above, or perhaps cache it somehow?).  
  * If not, skip the aspect section
  * If so, display the section and associated attributes.  We could even set off these attributes in a well and display the aspect type label if we want to get all fancy-like.

Thoughts? @benallenallen @joehof @cmlewis @dgrumieaux @zkeller

**Comment by dgrumieaux** [comment]
Would we want to configure forms the same way we do now, just with aspect-granted properties as additional options? Then if the node does not have the aspect, the property does not show up? That way we can order aspect-granted properties however we want with the regular type-granted properties.

**Comment by gsteimer** [comment]
Maybe.  I know that when Ray has talked about it, he's always envisioned having each aspect in it's own section.

**Comment by cmlewis** [comment]
@dgrumieaux @gsteimer I'd much rather be able to intersperse aspect properties throughout regular properties. I don't want us to pigeon hole ourselves into having to group them. Instead we could consider adding general groups to properties so you could put whatever you wanted under each group/heading.

**Comment by gsteimer** [comment]
Agreed - I like that better too

**Comment by dgrumieaux** [comment]
@cmlewis - Agreed. Then if the aspect isn't on the node, that property just doesn't show up.

I know for a client there was a "grouping" done to formSupport, but I believe that was a while ago. Would that be addressed within forms themselves, or perhaps some concept of a composite form?

**Comment by cmlewis** [comment]
Yeah, I think you'd just set that up in the form itself. I know there is already the concept of 'secondary group' that search uses for the 'more' section, so we'll have to make sure we don't break that.

**Comment by cmlewis** [comment]
Interesting suggestion from a client - not only adding non-mandatory aspect support, but potentially also supporting attributes from any of the type's subtypes. So when searching, the user can pick and choose attributes to search on.

Search Example:
- User selects trac that searches on generic Insurance Document
- Advanced search and table view configured to show Insurance Document attributes plus Policy, Claim, and Customer Document attributes (subtypes of Insurance Document)
- User searches on whatever combination of attributes to get back all docs or folders needed.

Above scenario would work well for Customer Service, who wants to search across all folders related to a customer, which could be Customer, Claim, or Policy folders, all in one view.

**Comment by gsteimer** [comment]
As of HPI 2.6 we now have a Non-Mandatory aspect config in HPI admin.  See also #1499

**Comment by wrudnickTSGRP** [comment]
Revision: 18890
