### ISSUE TITLE
Send Email Body Validation No Longer Works

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/HPI#1091]
Per the below screenshot, validation on the body of an email no longer works. It used to and should require text to by typed into the body before you can click "Send Email".

![send email body validation](https://cloud.githubusercontent.com/assets/4128978/15049491/324111c2-12b4-11e6-8e0d-5225772b130b.gif)

**Comment by nquillin91** [comment]
Picking this up for Gallagher Bassett, fixing the error handing as well.

**Comment by nquillin91** [comment]
Fixed with revision 15144

sendEmail - Removed remaining knockout associated with error-handling and switched over to jQuery based error handling via backbone model which fixed the no-body validation issue, also modified addTo, addCC, addBCC for validating typeahead values when directly triggered through the sendEmail method. 

sendEmailSpec - Overhauled to represent changes made when knockout was originally removed as well unit tests were added for the newer changes that were made

Templates for sendEmail were modified with regards to the error message div now including the cid in the class name for specific accessing of each individual view's error message 

Github issue associated with changes - Send Email Body Validation No Longer Works #1091

CR - Devin S
