### ISSUE TITLE
Advanced Combine to PDF Add All then Remove All does not Repopulate Available Documents

### ISSUE THREAD

**Issue by dhartman25** [tsgrp/HPI#1107]
On first launch, if the user adds all then removes all documents, the available documents does not repopulate with documents again. If any single documents are added and then removed, both Add All and Remove All work properly afterwards.

![advanced combine to pdf add all remove all](https://cloud.githubusercontent.com/assets/4128978/15612638/453bfeca-23f5-11e6-8036-e8bc5261e095.gif)

**Comment by nquillin91** [comment]
Fixed with revision 15199

ADVANCEDCOMBINETOPDF MODIFIED - Changed data being stored in arrays to data being stored in collections and made them global for easy access. Issue was originally array values (which are now backbone collections/models where appropriate) were being emptied out. 

***NOTE - SelectedDocuments, FilteredDocuments, and AllDocuments are all in sync and have been switched over to backbone collections as of this revision

CR - Devin S
