### ISSUE TITLE
Searches with a Colon Character Produce Unexpected Searches

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1134]
See the two below videos, but two different (and both "wrong") things happen when a colon is used in a fulltext or attribute search. It doesn't seem to matter if you are using Documentum/Alfresco/Solr as your backend. 

It appears that HPI is attempting to send over the query correctly for fulltext searches, but by the time it gets to OC, it seems to have dropped everything after the colon. The attribute search also appears to send it correctly on the network tab, but OC messes it up when it gets to OC, so might be jackson messing with the serialization?

## Fulltext:
In this case, it seems to only be getting the part before the colon.

![vers](https://cloud.githubusercontent.com/assets/4850976/16627387/aa1e0a6c-4372-11e6-807e-633697021435.gif)

## Attribute:
In this case, it seems to totally jack up the query that is getting parsed by OC:

![vers2](https://cloud.githubusercontent.com/assets/4850976/16627540/54b5adea-4373-11e6-8940-25285a9360a0.gif)

**Comment by ZachGerth** [comment]
Enabled FTS to now "pass through" the colon character with OC Revision # 14817.

**Comment by renesaladrigas** [comment]
Changing the delimiter from the token ":" to being the token "~:~" so that searches that include a colon will work as expected. This update will change the delimiter for regular HPI searches as well as composite searches in HPI and be expected and parsed as such in OC.

Fixed with HPI revision 16195 and OC revision 15294
