### ISSUE TITLE
Folder Notes - Export Excel and PDF

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#1152]
Currently on Edge2, neither the Export all notes to Excel nor the Export single note to PDF are working. In addition, their info icons in the config do not describe their functionality.
<img width="199" alt="screen shot 2016-08-03 at 11 22 33 am" src="https://cloud.githubusercontent.com/assets/8796489/17373162/9f57e8d6-596c-11e6-9b87-9d4f4bf9a5a0.png">

The icons above reference Note Visibility instead of their actual functionality.

**Comment by renesaladrigas** [comment]
FOLDER NOTES -- Correcting HPI issue 1152. Folder notes were not being exported properly (in Excel or PDF format) since OC was expecting every folder note to have an embedded link in the "note_details" property with the folder Id where this note is located. We are now receiving that Id as a parameter from HPI to avoid any unwarranted assumptions by OC. This revision also cleans up the code around this action on the OC side by avoiding repeated or misleading logic in for loops.

Files modified:
foldernotes.js & foldernotesconfig.html
Action js file now passes the folder Id as a parameter. HTML file displays the correct informational message for this action.

RestEndpointConstants.java & RESTAction.java
Created a new constant for this action's endpoint.

FolderNotesActionExecuter.java
Updates include: Passing in parentId property used to create link to owning folder. Looping logic is now based on the attributes we use to build PDF or Excel outputs, not based on all properties (why loop through all when you don't need it?). Properly escaping HTML in the display of both Excel and PDFs. Removal of repeated/unnecessary logic.

Issue corrected with HPI revision 16108 and OC revision 15247
CR - Bradley White
