### ISSUE TITLE
Recent Objects Dashlet Config is confusing and doesn't work properly on selected type

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/HPI#1215]
Quite simply, this configuration is confusing. 

As a first timer configuring this dashlet I had a hard time figuring out what was going on in the configuration page, since there are two options to select a type for the recent objects. It seems like regardless of what is chosen on the right side (any "Folder" sub-type), HPI will always use the "Folder" (parent such as dm_folder or dm:folder) as the type it uses to show the recent folders. As a result only attributes related to the parent "Folder" type will show up in the dashlet.

This is a screenshot of what the configuration looks like (a sample taken from edge1).
![recentobjsdashletincorrecttypes](https://cloud.githubusercontent.com/assets/14186921/19483285/7604675a-9519-11e6-88ce-3d7e33b02189.PNG)

Here's a screenshot of the resulting dashlet.
![recentobjsdashletsample](https://cloud.githubusercontent.com/assets/14186921/19483551/5fc97628-951a-11e6-9867-6e9c3ba05fe9.PNG)

Clearly, only the attributes pertaining to the parent "Folder" type show up. This happens since the model saves the value "Folder" as its type, not the subtype that was selected on the right, hence it cannot find the "policy_number" attribute.

Proposed changes:
- [x] Provide a better description for the configuration on the left, such as _Select type of related object_ (plus description below) and give options _Container_ and _Document_
- [x] Develop enhancement for this dashlet to support recently viewed documents
- [x] Keep the right hand side configuration and ensure the type selected on this side will actually be saved on the model so that the attributes selected will show up
- [x] Not pictured, but I also saw that if more than one Related Objects dashlet is configured ("Recent Type A Folders" and "Recent Type B Folders") they will both display the same label, not their own label. During development we should make sure this doesn't happen.

@gsteimer feel free to comment with any suggestions or correct my statements above

**Comment by gsteimer** [comment]
@renesaladrigas - you are correct.  The admin allows for more configuration than the dashlet actually allows.  The original vision was for this to be a recent objects dashlet, but we never got around to actually doing that.  I believe the front end code just assumes the object is a `Folder`.  The main enhancements would be to make it so that you can use other container types as well as documents, and have the ability to place more than one of these dashlets on the dashboard.

Also - I've noticed that the recent objects dashlet doesn't ever display any items in Documentum environments, so I'll add this to the list:

- [ ] Make sure that the dashlet works on Documentum environments

**Comment by tbrandstatter** [comment]
RECENT OBJECTS: **CURRENT RECENT OBJECT DASHLET MUST BE DELETED AND RE-ADDED* Updated recent objects so it can handle recent folders and recent documents. Now users can have more than one recent objects dashlet configured, each having the correct display attributes on the dashlet itself. Rearranged the recentObjects userpref to be an object that contains an array specific to each recent object dashlet that is configured. The dashlet-ids are now read only and must be unique when creating a new dashlet. Also renamed attributes and cleaned up the code to make more sense for the functionality.

CR: Nick and Graham

Fixed with Revision: 17691

**Comment by gsteimer** [comment]
This still is not working properly.  The configuration is clearer, but if you choose a custom folder type, it still only displays attributes for the root `Folder` type.  

If you configure this for Recent Folders and choose `Folder` on the left, but a custom folder type on the right, the following happens:

- [ ] Only the root `Folder` attributes are available for selection in the available attributes for dashlet columns
- [ ] No objects ever display in the dashlet after viewing a folder of the custom type

**Comment by gsteimer** [comment]
Ok - so this is really odd... My comment from above was based on a client environment on Documentum from a build on 12/1 (6 days ago).  I tried it today on edge1 and edge2 and it's working fine... 🤷‍♂️
