### ISSUE TITLE
Allow opt out of public saved searches

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1232]
Currently HPI always allows users to make their saved searches public.  Some clients may want to disable this behavior though.  If we were to do that, we would need something in the admin that says whether or not to allow users to make their saved searches public.

**Comment by ebrent** [comment]
2 enhancements relating to this:

1. ENABLE/DISABLE PUBLIC PREFERENCES IN SAVED SEARCH - Added to the search config to enable/disable public saved searches. Disabling public saved searches will not allow the user to publish saved searches from the user preferences page. 
OCMS revision #23745

2. PUBLIC SAVED SEARCH - added an enhancement so that public saved search is no longer fully "public.". Now you can specify groups in ocms search admin (per trac) so that not just anyone can delete a public saved search, edit one, or publish their own saved search to that trac. If you don't specify groups at all, everyone is allowed to touch that search (like how other group configurations work). Within this commit I also switched the saved searches buttons in search to be clickable all throughout, and not just on the gliphicon. Specs added to test this new functionality. 
OCMS revision #23912
