### ISSUE TITLE
Combine PDF - Available and Selected Doc views are too small when stacked

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1233]
When the Advanced Combine PDF action is in "stacked" mode, the views for selected and available documents are too small.  Here's an example with only three documents in the folder:

![image](https://cloud.githubusercontent.com/assets/1377228/20529578/3f05a69a-b096-11e6-8f6d-2ff1fc76399e.png)

![image](https://cloud.githubusercontent.com/assets/1377228/20529591/4723f19c-b096-11e6-9a8f-0e8136250c7e.png)

Currently, tabbed mode for this action looks great.  When fixing this, be sure to test tabbed mode as well.

**Comment by rosenoam** [comment]
Revision: 16683
Fixed issue where available and selected doc views are too small when stacked. Within the advancedcombinetopdf.js there was a section of code that was overwriting any css changes being made so that was removed. Added class in the advancedcombinetopdf.styl called tableBorderBox which is a div around the resultsOutlet and the selectedDocsRowToggle ids in order to differentiate the two tables from one another. Added some styling to the class to make it look pretty.

**Comment by rosenoam** [comment]
Scroll should not be popping up when there's available vertical whitespace on the screen
![image](https://cloud.githubusercontent.com/assets/22036850/20840120/b7788f08-b874-11e6-84eb-503bc7d899e8.png)

**Comment by rosenoam** [comment]
Revision #16789
Toggle events, adding and removing documents will not cause a double scroll bar anymore

**Comment by b-k-white** [comment]
This fix did not consider the save to repository version of combine pdf. Reopening.

![screen shot 2016-12-15 at 3 25 43 pm](https://cloud.githubusercontent.com/assets/8796489/21242629/d3644494-c2da-11e6-805b-ee87d61cb12b.png)

**Comment by rosenoam** [comment]
Advanced Combine to PDF "Remove All Documents" button does not remove all documents when in the modal. 

![removealldocumentsbutton](https://cloud.githubusercontent.com/assets/22036850/21279271/1e557250-c3a5-11e6-9eab-35ba71ff72fd.gif)

**Comment by rosenoam** [comment]
Revision #16852
Fixed the "remove all selected docs" and the save to repo styling issue.
