### ISSUE TITLE
Table View does not render with correct results when list view and/or grid view is also enabled

### ISSUE THREAD

**Issue by peterkk** [tsgrp/HPI#1253]
-When grid view is enabled, table view never renders any results

-When list view and table view ONLY are enabled, an OC error occurs, but table view renders the correct results

The error that occurs whenever either list view or grid view is enabled is as follows:
"An unexpected error occured. You may refresh to try your request again or contact your adminstrator with the follow message: 12/6/2016, 12:00:09 PM Failed to get resource /alfresco/OpenContent/content/getAvailableThumbnails?objectId=undefined&amp;definition=hpiMedium 500 {&quot;status&quot;:500,&quot;message&quot;:null,&quot;error&quot;:true}"

**Comment by grahamsinger** [comment]
Update: currently when all three `searchResultViews` are enabled, switching to Grid or List view "works" (results show) and switching to Table view doesn't (results don't show).  

However, I noticed that when switching to either Grid or List view, another query is executed, whereas when switching to Table view, no additional query is sent.

The ideal fix would leverage the results we already have, but since there is server side pagination for Grid/List view, this could mean a more involved solution.

**Comment by gsteimer** [comment]
Marking this as high priority - I cannot use table view with collections on edge2 anymore because only grid and list view load properly.  Clicking table view brings back 0 results

**Comment by gsteimer** [comment]
Update - I can get collections to load if I first search for objects on a trac that only uses table view.

I think this may be a separate issue - it looks like it's looking to the last loaded search config to determine which views are used.


![collections-search-result-views](https://cloud.githubusercontent.com/assets/1377228/20980267/77a99a98-bc75-11e6-8749-b69620b941b3.gif)

**Comment by gsteimer** [comment]
Moved the above item to a new issue: #1256 - this is high priority, so removing that designation from here

**Comment by gsteimer** [comment]
Is this possibly related to #1042?

**Comment by grahamsinger** [comment]
Closed with rev16821
