### ISSUE TITLE
Search visibility and hidden fields are not being saved correctly 

### ISSUE THREAD

**Issue by Kovacinski** [tsgrp/HPI#1315]
Hidden fields do not get saved
![visible fields](https://cloud.githubusercontent.com/assets/7279444/23139635/0a9d21a2-f773-11e6-9d23-ddf2795d6199.gif)

**Comment by Kovacinski** [comment]
Issue is the if statements at lines 187 and 197 in the genericresultconfig.js. Those lines were added to fix an error that removing the last item from either visible or hidden does not remove the item from the model. For more info talk with Stephen or Devin S.

**Comment by renesaladrigas** [comment]
SEARCH CONFIG -- Visible and hidden fields were not being saved when added in the toss-across, since the code was always expecting at least one element in the model for each visible and hidden fields for any others to be pushed to the model. This was corrected by removing that if statement.

CR - Devin Swenson and Michael Holwey

Fixed with revision 17355
