### ISSUE TITLE
Object Type Configuration Caching

### ISSUE THREAD

**Issue by ZachGerth** [tsgrp/HPI#1321]
Right now, we cache the Object Type Configuration relatively aggressively in HPI. When it is first needed, it is cached to the _browser_ localstorage, and is pulled from there whenever it is needed. On logout, this localstorage is cleared.

This works well enough at reducing the amount of times our repositories have to access the configuration, and return it to the user. However, it presents a few issues in certain situations.

- [ ] For SSO implementations, the user typically never logs out of the application. This prevents the localstorage from being cleared. This alone isn't an issue, unless the OTC is ever changed.
- [ ] If the OTC is changed either then or during active use of the application, and a form references a changed attribute, users will not see this change. This normally presents as forms never rendering for users.
- [ ] There are two methods for fetching the OTC in our context implementation - both of these duplicate the logic of saving an OTC fetched from the server to the browser. With this logic there, developers who have to customize the cache have to maintain two separate locations.

This enhancement consists of one of two fixes.

1. Do we need to cache this OTC anymore? I have seen larger ones of a couple megabytes, but they typically average in the hundreds of kilobytes. We could do a "soft cache", outside of localstorage, as we do for other configurations, to prevent network calls.
2. If we need to cache this, we should append some sort of attribute - such as a modified date - and use that to determine, with a new endpoint, whether a new OTC needs to be fetched and stored in localstorage.

**Comment by gsteimer** [comment]
Bumping the priority of this since I think it's something we'll want to address sooner rather than later..

**Comment by renesaladrigas** [comment]
OBJECT TYPE CONFIG -- Removing the logic that caches the OTC in localStorage, and replacing it with a "soft cache" (just storing a copy of the OTC in javascript memory).

File modified:
context.js - Saves the adminOTC in a variable called "currentAdminOTC" as a soft cache any time the OTC is requested.
objecttypeconfig.js - When saving the OTC, we are no longer saving the model on the localStorage.
formconfig.js - Due to a race condition, the form config page was not rendering properly since the network call to the adminOTC was taking too long. Moved the logic in the beforeRender to the callback of the adminOTC to avoid this issue.

Also including changes to listview.js and listviewSpec.js so that unit tests for contextSpec.js pass properly. In listview, there were knockout variables that were causing additional network calls to adminOTC that ended up breaking the new tests.

CR - Zach Gerth

Fixed with HPI revision 17618

**Comment by gsteimer** [comment]
Reverted with HPI Rev #17625.  For some reason, searches do not display properly in any environment on Chrome:

![search-table-disappears](https://cloud.githubusercontent.com/assets/1377228/24413120/1c6081c4-13a0-11e7-957c-ed2a8da45065.gif)

**Comment by renesaladrigas** [comment]
Commit 17618 was reverted due to some issues seen in trunk on multiple edge builds as seen in the descriptions above. Revision #17634 in HPI trunk fully replaces the aforementioned commit.

CR - Zach Gerth

**Comment by renesaladrigas** [comment]
Some logic related to the OTC stored in the localStorage was left behind in security.js. Commit #17653 takes care of this removal and should be picked up in tandem with commit #17618 during a merge of this enhancement.
