### ISSUE TITLE
Bulk Property Edit Action - Should not enforce required validation on bulk page

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1323]
In the Bulk Property Edit action, the user should be able to fill out one or more attributes and click the save button right away.  However, it looks like the action is enforcing the required validations on the form:

![image](https://cloud.githubusercontent.com/assets/1377228/23758078/2dcc0e3e-04ae-11e7-9fcb-da0475dc0ad1.png)

This means that it's impossible to reuse the typical `viewProperties` form across the View Properties action and the Bulk Property Edit action.  In the case above, you'd have to enter an Object Name on the bulk page, which would render the action useless.

As a workaround, you can simply configure a new form to use in Bulk Property Edit, but it'd be much nicer to simply reuse the `viewProperties` form.

**Comment by renesaladrigas** [comment]
BULK PROPERTIES -- Removing "required" validation from bulk properties page, but keeping validation on individual pages if the user decides to traverse through each document's properties. Included in this commit is changing the name of the "enabledValidation" parameter in formsupport.js to "enableRequired" since it is more descriptive of the current functionality of the parameter; validation always occurs.

CR - Joe Hof

Fixed with revision 17699
