### ISSUE TITLE
Email Attachments - Not listing any attributes

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1325]
See below - when trying to view available documents to attach in the Send Email action, all of the items are blank:

![image](https://cloud.githubusercontent.com/assets/1377228/23759381/4219f5d2-04b2-11e7-8b78-84ef6724ff97.png)

I'm guessing we're trying to use this configuration in the admin to set up the attributes to display:

![image](https://cloud.githubusercontent.com/assets/1377228/23759425/64e0b362-04b2-11e7-9fff-10635d91741b.png)

In the screenshot above, I've selected Name and Modified Date, but the attachments section is still blank.

**Comment by gsteimer** [comment]
Note - the same thing happens in the "attached items" tab as well:

![image](https://cloud.githubusercontent.com/assets/1377228/23759525/aadad208-04b2-11e7-8782-28e9fdc4803a.png)

**Comment by renesaladrigas** [comment]
The issue here seems to be with the admin configuration for this action. Most importantly, it seems like the configurations will not persist properly on the model, but there are other enhancements that need to be done. Here's a list of what needs to be done:

**Admin Side**
- [ ] Make sure the admin only allows for one object type to be configured to display attributes. If the object type is changed, the previously configured attributes should be cleared to allow for new configurations.

- [ ] Ensure these changes persist in the model.

**Action Side**
- [ ] Make sure that any attributes not found on the OCO are ignored so as to avoid tables full of "undefined"/"null" columns.

**Comment by renesaladrigas** [comment]
SEND EMAIL ACTION -- The send email action was not abiding properly to the configuration that it was given in the admin. The listener in charge of performing changes to the model was being obscured by an attempt to "clean itself up". Now, the configuration will retain any changes made to the attributes selected via this listener, keeping a list of attributes to display in email attachments for a single object type that was configured.

HPI Revision: 17485

CR - Marc Brouillette

**Comment by gsteimer** [comment]
@renesaladrigas - it looks better, but it seems like dates aren't formatting properly.   Dates should format as specified in the AppConfig:

![image](https://cloud.githubusercontent.com/assets/1377228/23960582/65a4aa06-0976-11e7-83c3-819c4529e8f4.png)

**Comment by renesaladrigas** [comment]
SEND EMAIL -- Dates were not being formatted for the attributes chosen to display for email attachments, now they will be formatted with the format chosen in the application config.

CR - Marc Brouillette

Fixed with revision #17550
