### ISSUE TITLE
Forms are backwards when inheriting from another type

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1340]
In form config, it's possible to tell a form to override with another type's form.  This is useful when you have a common parent and subtypes, but you want the subtype forms to all look the same based on super type attributes.  

We have this setup on release2/edge2 in the Engineering trac.  For example:

![image](https://cloud.githubusercontent.com/assets/1377228/24268100/88a74404-0fda-11e7-9478-f7c530aa0bfc.png)

The parent type form looks like this:

![image](https://cloud.githubusercontent.com/assets/1377228/24268119/955e6cfe-0fda-11e7-912a-95ebd1d1cb0a.png)

However, when viewing a document's metadata, the properties are reversed:

![image](https://cloud.githubusercontent.com/assets/1377228/24268155/ac8990b6-0fda-11e7-9120-17e5b0814156.png)

**Comment by grahamsinger** [comment]
@gsteimer Figured out what was happening, and have a fix.  One thing I wanted to double check on (that I'm pretty sure we've talked about before): if the form with the override has properties configured, should the "override" form's properties get tagged on at the bottom or put on top? Or, does it matter?

**Comment by gsteimer** [comment]
@grahamsinger - I think it makes sense to put the extra properties on the bottom

**Comment by gpolonus** [comment]
Fixed with commit #18132

**Comment by gsteimer** [comment]
Looks like something has undone this fix.  Looking at a form that inherits from another type on release2 and the form is backwards:

This is an engineering drawing, which inherits it's form from engineering document:

![image](https://user-images.githubusercontent.com/1377228/50979351-e4b4ba00-14bb-11e9-8204-5cbe93298e6a.png)

Admin:

![image](https://user-images.githubusercontent.com/1377228/50979370-eed6b880-14bb-11e9-83fb-06b18090e30a.png)

**Comment by renesaladrigas** [comment]
This issue has been previously fixed with revision 20303.

This issue is causing problems with cascading picklists. Since the order of the attributes is reversed, the dependent control is evaluated before the control it depends on, causing the dependent control to evaluate the value incorrectly and display a blank.

**Comment by renesaladrigas** [comment]
FORMSUPPORT - When overriding one type's form with that of another type, there is no need to reverse the array. This line of code is no longer required because of the proper refactoring of the getFormTypeConfig method in context.js done by gsinger in revision 20794.
Revision: 22424

CR - gsinger, dvora
