### ISSUE TITLE
Email Relationship not getting created on Alfresco upon MSG import

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1357]
When uploading a MSG file that has attachments, we create an `hpi:emailed` relationship with the email as the parent and any attachments as children.  This functionality works on release2 (built on 4/1) and on edge1 (documentum), but is not working on edge2:

Viewing the email should display attachments relation:

![image](https://cloud.githubusercontent.com/assets/1377228/24814040/d707b6b2-1b95-11e7-8eb5-e1772c631023.png)

Admin console - no associations on email:

![image](https://cloud.githubusercontent.com/assets/1377228/24814069/e7081656-1b95-11e7-8796-3102c425cf58.png)

Marking as high priority since this should work for demos. FYI @benallenallen

**Comment by renesaladrigas** [comment]
So this issue seems to be coming and going, so in order to ease debugging in case this resurfaces, here are a few places to start looking into to make sure the association is properly set:

- BulkUpload.HTML5UploadControllerView._doXHRUpload() -- make sure that the `action` param that is passed into the request contains the correct association, in this case `hpi:emailed`.
- AddDocumentActionExecuter.java createEmailAttachments() -- here is where the association is actually set, based on the parameter defined by the constant `PARAM_EMAIL_RELATION_TYPE`. follow this code to ensure the relation is properly set.

**Comment by gsteimer** [comment]
Adding to @renesaladrigas's note - the actual relationship is set in `EmailUtil#relateAttachmentsToEmail`

**Comment by gsteimer** [comment]
closing this - I can't reproduce this anymore on release2 or edge2
