### ISSUE TITLE
Delegate Workflow Task to Utilize Workflow Forms 

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1383]
Currently delegate workflow utilizes hard-coded HTML / ajax calls to allow a user to delegate a workflow to another user. 

Apart of a client request to update delegate workflow action to utilize workflow forms instead.

**Comment by tbrandstatter** [comment]
DELEGATE WORKFLOW TASK: ***Requires OC Revision:  16477 *** delegate workflow task now requires a configured form using bpm_assignees. Added audit log entry and document notes integration that are configurable. Added spinner that can be triggered if form support external rules is validating. 

Fixed with Revision:  17898

CR: Nick

To configure workflow form for delegate task: https://github.com/tsgrp/HPI/wiki/Workflow-Form-Configuration
