### ISSUE TITLE
Workflow Info Stage Module

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1385]
Functionality is being added that includes the ability to display workflow information when in stage on a document that has a workflow started on it. Being merged in.

**Comment by tbrandstatter** [comment]
WORKFLOW-INFO: GitHub enhancement: https://github.com/tsgrp/HPI/issues/1385  Configurable in the stage admin, workflow info is a module in stage that displays the properties of the workflow that is on the document currently being viewed in the stage. If there is no workflow, the workflow info toggle will not appear.

CR: Nick

fixed with revision:  17856
