### ISSUE TITLE
TableView Doesn't Work With Scrolling

### ISSUE THREAD

**Issue by peterkk** [tsgrp/HPI#1416]
Facet Search does not function correctly when the top of the table view is scrolled past the top of the screen. 
When you click on various filter options for facets with the table view at the top of the screen, it works fine. But when you scroll past the top of the table view, then clicking filter options doesn't render the first row in the table anymore.

![facetsearch](https://user-images.githubusercontent.com/14186903/27052205-8dd1df0a-4f7e-11e7-93d3-81cd6627bf18.gif)

**Comment by renesaladrigas** [comment]
This issue seems to be unrelated to facets or search, it simply seems to happen when scrolling up and down the results page for a search. See below:
![tableviewscrollingdoesntrenderresults](https://user-images.githubusercontent.com/14186921/27104201-087949c8-5051-11e7-9310-30425ef79987.gif)

**Comment by gsteimer** [comment]
@renesaladrigas - does the problem only occur if the left side criteria causes the page to scroll?  Just wondering because if I search on the insurance trac on edge2, it seems to work fine (except for the table column header overlapping the HPI header, which is annoying):

![tableview-scroll-working](https://user-images.githubusercontent.com/1377228/27133954-9aa83a38-50d9-11e7-9c7c-b003db4256d6.gif)

**Comment by renesaladrigas** [comment]
SLICK GRID -- Correcting the bindings that were added to slick grid for thumbnail updates. All thumbnail logic is properly wrapped in an if statement so the viewer and event bindings specific to thumbnails do not interfere with the default behavior of slick grid for traditional tableview implementations.

Fixed with revision 18156

CR - Graham Singer & Joe H(aynes)
