### ISSUE TITLE
VAD—Config Discussion

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/HPI#1429]
Currently, View All Documents uses a SearchConfig.  However, as I've looked into some enhancements for VAD, I discovered that there were a handful of config options that were once in a VAD CustomConfig, but aren't any longer due to the switch to using a SearchConfig.

Do we always want VAD to use (only) a SearchConfig?  I.e will any enhancement to Search or VAD always be done in the SearchConfig—exposing the functionality to both scenarios? Or, should we consider if something is simply a "VAD enhancement" and add those things back to the CustomActionConfig?

For reference, the following seemed to be in the old VAD Aciton Config:
- A Date Filter
- Ability to show if a Doc was redacted, annotated, etc

@gsteimer thoughts?

**Comment by gsteimer** [comment]
Ideally those things would just be part of the SearchConfig since it'd be no different than executing it from search.  The date filter makes sense to me, but the second bullet we've always had to be careful with.  Those features were dropped from VAD in Watermelon Hound's revamp because they were concerned about performance (displaying thousands of results in a folder) and those operations are expensive since they don't come back in search.  For items that do come back in search (ex: `lockOwner`), you can use the Search Indicator icon config.

**Comment by gsteimer** [comment]
Based on further discussion - VAD can eventually have more config options separate from the search config.  However, these should be things that are not related to the interface that is shared between VAD and normal search results.
