### ISSUE TITLE
Cannot view folder properties in the stage after updating properties

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1540]
Steps to recreate:

1. View a folder in the stage
1. View properties and make an update.  Should save and update fine
1. Try to view properties again.  The modal will not load, error in the stage is:

![image](https://user-images.githubusercontent.com/1377228/33334673-4cc3958a-d430-11e7-8fb6-eca5db9fff14.png)

Note - this only happens for folder properties in the stage.  Document properties seem fine, and editing folder properties from a modal launched from search results seems fine too.

**Comment by Swence32** [comment]
Talked with @nquillin91 about what's happening. When an action is executed, we unset the conditions and ocActionId off the action model before sending it to OC, presumably so Jackson can parse the JSON and create the POJO properly. However, that causes the action model to now not have the conditions, so the next time the action is launched it fails to check the non-existent conditions. 

I believe we got around this in the older FolderActions because we were re-creating the folder actions every single time an action is launched, so it was always refetching and evaluating what actions should appear. I'll talk with @dgrumieaux about what the best solution will be.

**Comment by Swence32** [comment]
The easiest solution here per the OC/HPI group is to perform a full re-fetch of folder actions and re-render the action views when an action is executed.  Would need to trigger something from Action.js to tell FolderActions to perform the fetch and render

**Comment by Swence32** [comment]
Resolved. Add trigger to Action.js execute. FolderActions listens to trigger and does a fetch and rerender when an action is executed. Fixes issue where ViewProperties would not load after previously executing the action.

Commit #19334
