### ISSUE TITLE
Double scroll bar appears in stage

### ISSUE THREAD

**Issue by joehaynes** [tsgrp/HPI#1546]
When initially loading a document in the hpi docviewer, a double scrollbar appears. If the user does any modifications to the docviewer, such as opening another pane or resizing the window, the scrollbar is removed.

In order to recreate: 
- load a document from Search or View All Documents
- make sure the window is wide enough to not enter "tablet" mode

The function that gets fired to remove the scrollbar is 'windowResizePanes' in stage. However, it is getting incorrect values for the size of the viewer on the initial load compared to when it gets called after the page has loaded.

![doublescrollbar](https://user-images.githubusercontent.com/22036837/33673971-dcfd9274-da73-11e7-8a98-caf1e9680744.gif)

**Comment by wrudnickTSGRP** [comment]
@joehaynes did you fix this issue and not close? I haven't been able to recreate it and it looks like you made a few commits related to DocViewer at the end of last week

![docviewer](https://user-images.githubusercontent.com/32521696/33843172-4245af1c-de62-11e7-8a5b-be67c9939919.gif)

**Comment by gsteimer** [comment]
@joehaynes @wrudnickTSGRP - any update on this?

**Comment by wrudnickTSGRP** [comment]
I actually have been unable to replicate the issue locally since it was assigned to me

**Comment by joehaynes** [comment]
I am still able to replicate it on edge

**Comment by gsteimer** [comment]
I'm now also seeing double scrollbars when View All Docs is loaded.  

![image](https://user-images.githubusercontent.com/1377228/36919234-42ef047c-1e22-11e8-8ad4-1a7575a16863.png)

Perhaps its a downstream effect since VAD is the auto-launch action, but Send Email has double scrollbars as well:

![image](https://user-images.githubusercontent.com/1377228/36919218-34e1cfa4-1e22-11e8-96f1-b1638e844bc1.png)

**Comment by gsteimer** [comment]
From looking at this more, it seems to be any full pane right side action is getting this scrollbar

**Comment by acastor** [comment]
Revision: 20163

RIGHT SIDE ACTION HANDLER DOUBLE SCROLLBAR: Reducing the right side action handler's min and max heights to prevent the double scrollbar from appearing. Also replaced resizing logic from stage.js that set inline css with CSS media queries. 

CR: Marc, Joe Haynes

**Comment by acastor** [comment]
@gsteimer The commit above should eliminate the double scrollbar in right side action handler. I'm leaving this issue open because I did not address any issues with a double scrollbar in docviewer

**Comment by keljopap-tsgrp** [comment]
Revision 21750:

DOCVIEWER REFACTOR:
-Separated logic that determines viewers based on their mimetypes/object types/renditioning status into contentviewer.js, allowing you to be able to render any viewer in a new tab view, along with the ability to configure whether images will be streamed or opened in "docviewer" mode (includes the toolbar)
-Stripped out all custom resizing logic from the Viewers and replaced it with a CSS solution that sets an action bar of constant height such that the content will fill up the rest of the docviewer pane (this should resolve the double scroll bar that was previously appearing when resizing triggers were conflicting)
-Made the viewers fill up 100% of their parent objects' space so they will adapt to the pane containers in stage or to the whole window in the new tab
-Fixed heights for stacked panes so that the left bar is directly above the panes, the panes are of equal size, and not overlapping one another
-Added a new route for the new tab doc viewer in router.js
-Added tsg util calls for ajax calls made from the contentviewer 

CR: Dhruv, Marc, Alex

**Comment by keljopap-tsgrp** [comment]
@gsteimer The commit above should eliminate the double scrollbar in docviewer.  I could not replicate with any combination of viewers, even by zooming in upward of 200% in which case it just goes to the stacked panes view.
