### ISSUE TITLE
Search - Pagination is not updated until after a button click

### ISSUE THREAD

**Issue by henryerzinger** [tsgrp/HPI#1562]
After running a second search, the pagination dropdown is not updated until a button is clicked or a dropdown option is selected: 
![pagination_error](https://user-images.githubusercontent.com/14202907/34425068-6696d1cc-ebee-11e7-8126-cbff2f9b8eee.gif)

**Comment by renesaladrigas** [comment]
SEARCH / TABLEVIEW - Removing a lot of code to clean up the performance of search, based on the listeners triggered. The biggest change in this commit is the change in tableview.js, where we are now listening on the single point of communication between ocquery.js and tableview.js: the listener 'query:complete'. This listener will mark one single completion of a query, thus rendering tableview and the rest of the modules dependent on it correctly.

Fixed with HPI revision: 19729

CR: Joe Hof, Dan Grumieaux
