### ISSUE TITLE
Cannot finish an AW form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1594]
Not sure if this is related to the recent dependency updates, but you can no longer complete an Active Wizard form on edge1 or edge2.  It gets stuck spinning here: 

![image](https://user-images.githubusercontent.com/1377228/35406387-62b47ffa-01ce-11e8-81e8-49f790b028df.png)

Notes:

- No errors in the logs or console
- It seems like the object is actually created (first time through) or versioned properly (after resume form) depending on how you edit the form
- Save and Exit works properly
- After the page gets stuck, you can't click on any of the header links.  This leads me to believe there's something wrong in the JS layer, but it's odd that I don't see any errors in the console

**Comment by grahamsinger** [comment]
Took a quick look at this because I'm doing wizard work.  What's happening is the URL isn't getting changed to `/submit`.  Currently in the code we have 
```
   Backbone.history.stop();
   Backbone.history.navigate(url, { replace: true });
   this.navigate(url);
```
It seems like calling `stop()` on `Backbone.history` doesn't allow it to fire when we try to call `navigate()`, but I'm sure there was a reason why we stopped it in the first place? (so that the user couldn't hit back and re-submit?)  Therefore, more research is needed before we simply take out the `...history.stop()` call.

**Comment by gsteimer** [comment]
@grahamsinger - I think that's exactly it... We didn't want a user doing this:

- finish a form
- click the back button
- be taken back into the form when the resume form action wasn't run (and never checked out the form)

**Comment by dgrumieaux** [comment]
So this is what `stop` looks like in our version of Backbone:
```
    // Disable Backbone.history, perhaps temporarily. Not useful in a real app,
    // but possibly useful for unit testing Routers.
    stop: function() {
      Backbone.$(window).off('popstate', this.checkUrl).off('hashchange', this.checkUrl);
      if (this._checkUrlInterval) clearInterval(this._checkUrlInterval);
      History.started = false;
    },
```
I'm going to try to find a better way to do this...

**Comment by renesaladrigas** [comment]
ACTIVE FORM ROUTER - User wasn't taken anywhere after the form was completed due to Backbone's navigation being stopped and the JS layer frozen. We will not stop this anymore and navigate freely since we cannot go back to the form when hitting the back button through this router.

Fixed with HPI revision: 19745

CR - Graham Singer
