### ISSUE TITLE
Search sort order not consistent

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1609]
The sort order for searches does not seem to be consistent.  See the following example from edge2:

In the admin - claims should be sorted by claim number, ascending:

![image](https://user-images.githubusercontent.com/1377228/35823475-46bd47aa-0a75-11e8-8e33-c87ab5efe1b5.png)

The first search does seem to sort properly.  But if I search again, the sort is reversed:

![search-sort-order](https://user-images.githubusercontent.com/1377228/35823547-82211664-0a75-11e8-92db-ac7ecc80ad86.gif)

**Comment by joehof** [comment]
Small fix for sorting, this turned out to happen due to how Backbone.Pageable works and was covered up by us always running search through the router. Basically, Backbone.Pageable has a "directions" var defined, which maps order vars -1 to asc and 1 to desc, which were then overwritten on the query.state in OC and stayed that way. This messed up subsequent query.state maps and so we just kept the OC init default of "desc" on the state. We now remap -1 or 1 to the query state when it is returned from OC.

Fixed with HPI commit 19792.
