### ISSUE TITLE
AW Form Email on Reject has Incorrect Text

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1617]
If you reject a form, the text in the email is incorrect:

**Email Text**
![image](https://user-images.githubusercontent.com/1377228/36117850-c1dd8d9c-1000-11e8-8e0b-9f5dc50b1ee3.png)

**Form Audit History**
![image](https://user-images.githubusercontent.com/1377228/36117869-cef386da-1000-11e8-89ef-235867f00336.png)

**Comment by henryerzinger** [comment]
This issue appears to be more complex than we thought.  On rejection, formApproved never becomes false causing the approved message to appear in the email.  When the approvalDetails are retrieved, the details are correct.  However when we try to retrieve the content, the wrong input stream is brought back causing the wrong content url.  It appears that we are retrieving a stale approval details, instead of the updated approval details.  The status is "pending" and the comments are blank.

**Comment by gsteimer** [comment]
Note - need to test this on Alfresco 6.  According to @dgrumieaux - we have not seen this in Alfresco 6 environments.

**Comment by mwojno-tsg** [comment]
A temporary fix was put in place in OC commit #25224. The approval details were "fixed" before being passed to the send email. Fixed in the sense that the last signature was changed from "pending" to either "approved" or "rejected" based on what listener it went into/called from. The real issue at hand is a much bigger effort as approval details are successfully passed between wizard workflow listeners. See #https://github.com/tsgrp/HPI/issues/2107
