### ISSUE TITLE
Cannot finish form in streamline mode if form is not autonumbered

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1620]
When completing a form in streamline mode, if the form is _not_ autonumbered, the system lets the user name the form prior to finishing:

![image](https://user-images.githubusercontent.com/1377228/36213154-9a2b12f8-116b-11e8-89b8-25249463445d.png)

When I click the submit button, it fails with the following javascript error:

```
cancelcheckout.js:64 Uncaught TypeError: app.routers.activeform.submit is not a function
    at child.submitActiveForm (cancelcheckout.js:64)
    at HTMLDivElement.dispatch (jquery-1.9.1.js:3496)
    at HTMLDivElement.$event.dispatch (slick.core.js:75)
    at HTMLDivElement.elemData.handle (jquery-1.9.1.js:3172)
```

@aviking @nreiman - is this something that is caused by the fix for #1615 ?  Also - why is this getting into `cancelcheckout.js`?  I wouldn't think it should be cancelling a checkout, right?

Links for testing:

Simple CR is autonumbered: 
`http://edge1.tsgrp.com/hpi/activeform/Simple CR/streamline/new`

TS Leading Actions is NOT autonumbered:
`http://edge1.tsgrp.com/hpi/activeform/TS Leading Actions/streamline/new`

**Comment by aviking** [comment]
@nreiman this is caused because we changed the name of the "submit" function in **activeformrouter.js** to "finishAndSubmitPSI". The fix should be as simple is updating the line in **addformnamemodal.js** from _app.routers.activeform.submit(this.psi);_ to _app.routers.activeform.finishAndSubmitPSI(this.psi);_. Please make this change and test that it fixes this issue.

**Comment by nreiman** [comment]
HPI Revision: 19880
CR: NW

**Comment by nreiman** [comment]
HPI Revision: 19880
CR: NW
