### ISSUE TITLE
Predefined Views in Search are populated when user selects a trac instead of type

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1622]
The predefined views are being populated in search when the user selects a trac, This means that irrespective of the type that the user goes on to choose, the predefined views will be populated based on the type that was set by default when the user selected the trac. 
![rolebasedviewsearch1](https://user-images.githubusercontent.com/9989329/36279806-f36191a6-125d-11e8-8aee-f992776d3755.gif)

The roleBasedDropdown view should be initialized when the user selects a type.

**Comment by joehof** [comment]
While the code was working on the very first initialize of search, anytime the type was changed, the predefined view would not update. Added in a trigger from the searchside bar which has the predefined view update when the type changes. Also, took the opportunity to completely slash the app.context.currentTypeConfig() since it allows us to make dangerous assumptions other places in the application. Instead, for the initialize, we pass down the initial search type from the search router.

Fixed with HPI commit 19887.
