### ISSUE TITLE
Selecting a predefined view that has no results will prevent any results being displayed in View All Documents 

### ISSUE THREAD

**Issue by dhruvvora94** [tsgrp/HPI#1638]
If a user selects a predefined view which returns no results, then re-entering view all documents will not display any results. 
![rolebasednoresults](https://user-images.githubusercontent.com/9989329/36565120-22a348ba-17e5-11e8-9744-ac636e7951b0.gif)

When a user selects a predefined filter, it will get stored in their userpreferences. When a user enters view all documents, the predefined view is automatically applied. The timing of the filters being applied needs to be changed. 

The only way to recover from this is to go to search and select another predefined view ("All Results" would be easiest) or by blowing away user preferences. 

This issue is probably related to the fix for https://github.com/tsgrp/HPI/issues/1623

**Comment by acastor** [comment]
Revision: 19957

The View All Documents render was happening after Tableview and SearchResultControls were initialized but before Tableview and SearchResultControls had rendered.  Since the Tableview grid had not yet been created in Tableview's afterRender, when the predefined view was rendering, facets were attempting to apply to an undefined grid.

This case is now avoided by rendering View All Documents before creating and setting SearchResultControls. This is how View All Documents built up prior to REV 19923.

CR: Bradley and Rene
