### ISSUE TITLE
Bulk Upload - MSG plus attachments plus other documents fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1658]
See the screencam below.  Steps to recreate:

1. Use bulk upload to add an `MSG` file that contains attachments.  Ex: `demo-docs\Insurance\Quote for Public DNO.msg` _and_ at least one other document
1. Run through the normal bulk upload process to index the documents
1. After finishing, notice that the "extra" document added in step 1 gets properties from one of the MSG attachments.

![bu-msg-plusother](https://user-images.githubusercontent.com/1377228/36917458-7fee6b0c-1e1c-11e8-96c4-173210aa6a6b.gif)

**Comment by gsteimer** [comment]
Update - tried this with two "extra" documents on edge2 - looks like both my extra documents got properties of the attachments:

![image](https://user-images.githubusercontent.com/1377228/36917620-f2056470-1e1c-11e8-8b9f-70c539a2cc7c.png)

Trying with three "extra" documents, two fail and look to be getting properties of the two attachments, but the third document uploaded fine:

![image](https://user-images.githubusercontent.com/1377228/36917730-38455d14-1e1d-11e8-87a2-b9365680da6e.png)

**Comment by m-brouillette** [comment]
The problem is was specific to Synchronous Bulk Upload, and was that we assumed the # file = # of oco's, in synchronus BU, which is not the case with email attachments since we were filtering out attachments for upload.  We now filter the files within the upload method rather than before passing the file list in so that the indexes still line up.

CR - nquillin, gsinger
