### ISSUE TITLE
All Actions target the wrong document in dual pane

### ISSUE THREAD

**Issue by m-brouillette** [tsgrp/HPI#1663]
When two documents are open in dual pane, if an action is selected for either, it always acts on the document on the right side.  Shown here with the 'Annotate' action.

![hpi-wrong-anno-doc-dualpane](https://user-images.githubusercontent.com/8784115/37466570-1474741a-282c-11e8-94c0-bdc4cc678a16.gif)

**Comment by gsteimer** [comment]
Re-prioritizing this to UCR since:

- Most clients don't use this action if they're using OA since OA is embedded in the stage
- Even if you do want a way to launch the document in a new tab, you can do that with the External Launch Toggle configured on and for OA:

![image](https://user-images.githubusercontent.com/1377228/37466727-81a97fa8-282c-11e8-9968-edb2777b3ccd.png)

![image](https://user-images.githubusercontent.com/1377228/37466746-87ed4070-282c-11e8-955b-313020de231f.png)

For demos, this action was only used to launch images into OA since the image viewer has priority.  Once we remove the image viewer and have all that functionality in OA, we should remove this action from all demo tracs.

**Comment by m-brouillette** [comment]
If most clients do that, why do we still have two options other than Legacy support?  Less clutter is good.

**Comment by gsteimer** [comment]
Actually... it looks like this happens for _any_ action on the left side document.  We definitely need to fix this one.  For example, if you click to send notification, delete, download, etc on the left side doc, the action executes against the right side doc.

**Comment by henryerzinger** [comment]
It appears that when in dual pane view, both pane's share the same html IDs.  When actionClicked is called in docviewer.js, it does not know which pane's buttons were actually selected.  For example, both panes have div#downloadDocument.action-button-holder without any distinction between which one is actually being clicked on.  I tried adding a cid to the end of the class and ID but was having problems with the cid actually attaching to the class and ID.

**Comment by gsteimer** [comment]
Note - this also happens after you close the right pane.  So, for example:

1. Open document in left pane and right pane
1. Close the right pane
1. Execute an action on the left side (ex: view properties).  The properties for the closed document on the right will appear.

**Comment by joehof** [comment]
When opening docs in dual pane, we were seeing the second doc's action bar get replicated over the original doc's action bar, causing all actions run by either bar to be run against the second doc. The issue goes back to the docviewer action bar resize update, which added in a listener to the docviewer. Ultimately, the listener (and trigger) weren't scoped by moduleId, so any trigger would hit both docviewers listener's and thus cause the overwrite. This update correctly scopes some template divs and the name on the listener and trigger so the docviewer listeners no longer get confused.

Also, since this was just a scoping issue, no unit tests are needed since the real test here for the fix would be a component test with to docviewers running.

Closed with HPI commit 20443.
