### ISSUE TITLE
Adding Email Attachments Without the Actual Email Message - Always Fails to Properly Upload

### ISSUE THREAD

**Issue by nquillin91** [tsgrp/HPI#1673]
Scenario:
When adding an email with attachments and then removing the email itself from the list of documents to upload - the upload fails (ONLY FOR SYNCHRONOUS) 

Reproduction Steps:
1. Go to "Add Documents"
2. Add an MSG that contains one or more attachments
3. Remove the MSG and leave the attachment(s)
4. Proceed with the rest of the upload process
5. Once you click upload, nothing happens you just get a blank screen.

***This works for async uploads

![addingemailattachmentsonly](https://user-images.githubusercontent.com/13734523/37986217-831ba3e6-31c0-11e8-8810-7927cc2f43df.gif)

**Comment by gsteimer** [comment]
This isn't too surprising since on the OC side, I believe it expects to have the MSG file in order to strip off the email attachments again.  The OCOs on the bulk upload side do not actually have the content to send when they're uploaded.  I'm actually a little surprised that this works in asynch mode.

I'm guessing what we would need to do is either:

- Still send the MSG file, but mark it somehow that it shouldn't be added to the repo.
- Get the attachment content on the OCO on the BU side so that OC doesn't need to strip off the attachments again.

**Comment by nquillin91** [comment]
@gsteimer 

On the HPI side it looks like we are doing a check for "synchronousOption". When synchronous it shifts off the file and doesn't process a request if the file is an email attachment (assumption is made the original email upload will handle the uploading of the attachment)

However, when it async - we are specifically doing a check to see if we can find the email object (by ID) in the list of files to upload. If the email object no longer exists, we can say that the user removed the email object and we need to handle the attachment appropriately. 

The functionality that is in async needs to be correct for synchronous.

**Comment by nquillin91** [comment]
It has been determined that while async attempts to handle the removed email it still doesn't properly process the remove email all the time due to the Files / OCOs arrays that have to be in sync with each other (ie File[0] has to point to OCOs[0])

While attempting to upload a removed email sometimes shows as successful the handling is always incorrect

**Comment by kpelozatsgrp** [comment]
Revision: 20472
CR: Avi, Nick, and Steve
