### ISSUE TITLE
Export to Excel - Fails using right click action

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1689]
When using the export to excel action, it works fine using the Actions dropdown:

![image](https://user-images.githubusercontent.com/1377228/39016755-0024c182-43e7-11e8-84c8-e1517c9c2848.png)

But fails when using the right click action:

![image](https://user-images.githubusercontent.com/1377228/39016767-0af5b828-43e7-11e8-8626-e28b623a0921.png)

The error in the console is:

![image](https://user-images.githubusercontent.com/1377228/39016819-370ca656-43e7-11e8-8054-6140c58ef25f.png)

Sometimes the action just spins and sometimes I see this error as well:

![image](https://user-images.githubusercontent.com/1377228/39016861-49341ac6-43e7-11e8-92e5-f4443878b7fc.png)

**Comment by joehof** [comment]
This is an addendum to commit 19881, where we had to redo export search results to work consistently from search and VAD. In that commit, it was assumed the executeAction logic run from searchresultcontrols.js would also be hit when running an action from the right-click context menu, and this assumption was incorrect. To get export search results working from the context menu we just need to pass in the objectTypes from the search collection like we did in searchresultcontrols.

Also noticed that if choosing "select all results not on page" option, that the action dropdown for export was not working, although it WAS working for the right click menu action. This lloks to be because we only grab all id's when the "select all results not on page" button is clicked, but the right click menu saves us by also fetching all the names on right click. Added in logic that also grabs names when the "all" button is first clicked.

Since this originally went in without unit tests during unit test downtime, George has deemed this ok to go in without a unit test and one will be written later when a dev has time.

Fixed with HPI commit 20484.
