### ISSUE TITLE
Related Objects never loads sometimes on slow browsers

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1703]
In slow environments, particularly with slow browsers like IE 11, the related objects section never loads in the stage.  Example from a Policy folder on edge1 in IE11:

![image](https://user-images.githubusercontent.com/1377228/39819038-0659fd7a-5368-11e8-81ab-37b0da81a913.png)

The `Loading...` message never goes away.

I see these messages in the logs:

![image](https://user-images.githubusercontent.com/1377228/39819164-5cff6ba6-5368-11e8-8594-c13b3ed343bc.png)

However, that `indexOf of undefined` error _always_ appears, even when the related objects section loads properly.  For reference, the line it's failing on is:

```javascript
// check to see if the objectName has a period at the beginning (hidden) or if the objectId is the same as the
// current folder in the stage (this should always be defined by the time we get here)
var notHiddenNorCurrrentFolder = resultProps.objectName.indexOf(".") !== 0 && resultProps.objectId !== app.context.container.get("objectId");
```

**Comment by engerernoah** [comment]
ISSUE 1703 RELATED OBJECTS STUCK LOADING IN SLOW ENVIRONMENTS BREAKING SYSTEM TEST - In related objects once the query is done a knockout variable showRelatedObjectsSections is set to true once resolved = the number to resolve(lines 93-115). Through debugging it appeared that on slower systems when the error for 'unable to get property 'indexOf' of undefined' is hit before the showRelatedObjectsSections variable is set to true then the variable is never set to true because the browser runs without finishing the aforementioned section of code correctly. This keeps the observable set to false and in the html displays the loading and hiding the relatedObjects div. The error occurred on line 686 of folder tree because at times a resultObject comes in without any properties. This happens inside of a function call to filter the objects that are not hidden or in the current folder. The objects that are filtered are then used to reset self.query.fullCollection. To fix the issue if a resultObject comes in we return false since we do not want to add it to the filtered collection.

 Ability to test was limited because the issue was difficult to recreate locally, thus we made sure that adding and deleting documents work correctly as well as check to see that emails with attachments show their relation when viewed.

This issue will not be closed but rather monitored to determine if it does in fact fix the issue. 

CR Rene Nick

Issue 1703: https://github.com/tsgrp/HPI/issues/1703

**Comment by gsteimer** [comment]
Haven't seen this happen in STS since this fix so marking issue closed.
