### ISSUE TITLE
Saved Search Dashlet Actions - Displaying action ID instead of display label

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1714]
See the screenshots below.  When using actions in the Saved Search dashlet, the interface displays the action ID rather than the display name.

![image](https://user-images.githubusercontent.com/1377228/41061129-3f110b5a-6997-11e8-9ca9-f6c1fcdf5e4e.png)

Note the action label in the admin:

![image](https://user-images.githubusercontent.com/1377228/41061246-9ad7fe80-6997-11e8-8f9e-89d9b84fda78.png)

**Comment by engerernoah** [comment]
DISPLAYING ACTION ID INSTEAD OF DISPLAY LABEL- When clicking the action menu on the dashboard the actions displayed with their Id instead of their label, for example View Properties would display as viewProperties. To fix this I properly retrieved the label from the config and set the name of the object being pushed onto the menu to the label. 
Issue: https://github.com/tsgrp/HPI/issues/1714

CR: Rene and Joe
