### ISSUE TITLE
UpdateVersionHistory - not behaving properly in Alfresco 5.2.1+

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1734]
It seems as if something has changed with versioning in Alfresco 5.2.1 and above.  First noticed in the AW admin:

![image](https://user-images.githubusercontent.com/1377228/42842873-0dba26f6-89d4-11e8-8f3e-7f63a0eeb1f8.png)

When you publish a page set, the properties of the new version (in this case 1.1), are set to the same values as 1.0.  This happens when the `addRendition` method is called, which adds the json rendition, which calls `updateVersionHistory` (UVH).  Up to the point where the rendition is added, the 1.1 version looks correct.  But, as soon as UVH is called, the document properties revert to the 1.0 version.

Another manifestation of this is that the Activate process doesn't work.  All this code is trying to do is call `enhancedUpdateObject` to change the properties to point to the new active version.  However, it does nothing because UVH is called and wipes out the change.  Interestingly, changing the code to use `updateProperties(String, OpenContentObject)` works fine, but that's only because this code (for some reason) doesn't call UVH.

@grahamsinger is looking into whether or not 5.2.1 is affected, but my local 5.2.0 seems to work properly with the current codebase. 

For 5.2.1 and above:

- Is (finally) removing UVH an option?  We can try this, but we also need to make sure things like annotations on versions still work.  I.e.:
  - Annotate version 1.1
  - Version document to 1.2
  - Check to make sure annotations "stick" to 1.1
  - Annotate version 1.2, etc.
  - We'd also want to fully regression test the AW form workflow and compliance solution
- If the above doesn't work, the next option is to tweak UVH to work properly with Alfresco 5.2.1 and above.

**Comment by gsteimer** [comment]
For a non AW admin example, here's what's happening for docs:

1. Start with a doc that's NOT a PDF at 1.0.  Gets a PDF rendition upon import, looks good.
1. Modify a property (like folder tags) to something different.  Looks good.
1. Checkout the doc
1. Check in the doc with NEW CONTENT (something different so you can tell the renditions)

After the above steps, I'm seeing the content as wrong on 1.1 (the PDF rendition on 1.1 is actually the rendition from v1.0.  AND the properties are wrong.  So 1.1 has the original 1.0 folder tag, NOT the folder tag we changed it to in step #2.

**Comment by gsteimer** [comment]
Initial fix from @dgrumieaux with OC Rev 19554

Fix for downstream issue with AW Form autonumbering with OC Rev 19597.  If pulling these revs, you'll probably also want 19596 as well, which improves OC Events in general.

**Comment by dgrumieaux** [comment]
The solution commit in rev 19554 ensures property updates to a workspace://SpacesStore node are synchronized back to its corresponding versionStore node. This code is bound to the onUpdateProperties OCEvent by default.

This code replaces the legacy updateVersionHistory implementation, which previously deleted and recreated versionStore nodes instead of simply updating them. This implementation differs slightly from the old updateVersionHistory implementation. Recreation of nodes ensured that all node properties and associations were preserved. The new implementation of this method only covers properties - this covers properties, cm:content, and tsg:rendition content, but does not synchronize associations.

If there is Alfresco specific code that is not calling the OCEvent bound update methods (updateObject, enhancedUpdateObject, etc) this method may need to be manually invoked for property changes to be synchronized back to the version node.
