### ISSUE TITLE
Cannot load most folder actions after email sent

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1777]
See the screencam below.  After sending an email on edge1 or edge2, if you try to load most (see below) folder actions that are configured for full pane, it will fail to load.

![send-email-folder-action](https://user-images.githubusercontent.com/1377228/47580729-3dd96c80-d915-11e8-8476-a4c9fe20542b.gif)

Curiously, Folder Notes for some reason works.  However, VAD and Send email fail consistently (although work if you go to Folder Notes first).

FYI @benallenallen @acastor 

@nquillin91 - Guessing you may want to keep track of this one since it's present in the 3.1 tag.

**Comment by acastor** [comment]
@kforbes This appears to have been caused by commit 20887 in July. A line that shows the div that wraps the current action view was removed from the rightSideActionHandler.js insertSubView function. This line is required for the case where an action such as Send Email has triggered the showMessage event which hides the div.

**Comment by kforbes** [comment]
Closed with HPI revision 21921
RIGHT SIDE ACTION HANDLER - show content when inserting a subaction view, in case the previous subaction view had content hidden. RSAH will not show content if specified by the keepRSAHContentHiddenUntilSubActionCallsShow property on the action. Currently, all actions immediately show content except ACTPDF. 

CR - Steve, Nick
