### ISSUE TITLE
Tableview - right click with multiple documents selected switches to only one doc selected

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1805]
See the screencam below.  In tableview, right clicking with multiple docs checked cause the table to only select the row you right clicked on.  However, if you click _exactly_ between rows, it will work.  I couldn't get it to work in the screencam below.  This makes using the right click menu for group actions extremely frustrating.

![table-view-right-click](https://user-images.githubusercontent.com/1377228/50117104-a1935e00-0211-11e9-8521-3ab3e0b9889e.gif)

@keljopap-tsgrp @benallenallen - not sure who else has been changing table view recently, but please re-assign this issue if you figure out that another project's change is causing this issue.

**Comment by gsteimer** [comment]
Also note that this may also be affecting drag and drop of rows in the Combine PDF action.  If you click and drag _really fast_, it seems to work, but if you click normally, the whole cell changes to allow the user to edit the number.  See below:

![combine-pdf-reorder](https://user-images.githubusercontent.com/1377228/50119083-3ba9d500-0217-11e9-81d5-cf3d637908a2.gif)

**Comment by keljopap-tsgrp** [comment]
Yeah, looks like the initialization of the context menu is depending on the slickgrid event having all of those set as active, so we probably need a separate CSS class that means just "active" from a stage perspective.

**Comment by CRdouglas** [comment]
EDITABLE SLICK.GRID CELL ENHANCEMENTS: Allows the user to click inside of an editable cell and drag outside of the cell to select everything within that cell. Resets the cells active state to a normal state after leaving the cell.

Fixes previous commit - 22173

UNIT TESTS - Committing without unit tests so that other projects can move forward. Will be doing Unit tests in the future.

CR - Steve, Alex
