### ISSUE TITLE
Proximity Date Search - Past should include current day

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1868]
It seems as if the "past" option in a proximity date doesn't consider the edge case of something happening on a given day.  Here's an example:

On April 3rd, I Approved a couple documents.  However, when I search for documents Approved in the last day, no results appear:

![image](https://user-images.githubusercontent.com/1377228/55511542-77ca3f80-5626-11e9-85ce-cd379c358f0b.png)

If I search "within" 1 day or "next" 1 day, the documents do appear:

![image](https://user-images.githubusercontent.com/1377228/55511610-a0ead000-5626-11e9-8582-fd40245d9c39.png)

Note that it's approx 3:40pm when I'm taking these screenshots.  I'd expect that if I'm searching for documents approved in the past day, that documents approved earlier today would appear in the search results.

**Comment by gsteimer** [comment]
We should also test proximity dates for future as well.  I'm guessing the functionality just defaults to the current date at midnight vs. the current date and time.

**Comment by gsteimer** [comment]
Update - it seems as if this only happens on edge1 and works fine on Edge2

FYI @jackjbridge

**Comment by jackjbridge** [comment]
PROXIMITY DATE SEARCH: Proximity date searches for the next/past/within x amount of days, were going to that day at the beginning instead of the end causing docs that were in that timespan not to come back in the search. Set the end date to be used as the end of the day for each one to fix this.

SVN: 23007

CR: aking, nquillin
