### ISSUE TITLE
Impact Assessment - Action Executer Query Never Sets the Type

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1888]
The Impact Assessment action executer never sets the type that the query should execute against.  This will only ever work in Alfresco environments.  We still want to set it anyway for Alfresco - otherwise the query runs against the entire repository.

**Comment by ebrent** [comment]
IMPACT ASSESSMENT: Changed action executor to search only on documents of type specified. Passed through documentType in order to query this on the back end. Updated specs accordingly.  Also changed swallowing an exception to throwing one if an issue occurs.

Revision #22913 OCMS
CR: rsaladrigas, kforbes

Revision #22300 on OC
CR: rsaladrigas, aking, kforbes
