### ISSUE TITLE
OCMS Mobile Stage - fixes

### ISSUE THREAD

**Issue by ebrent** [tsgrp/HPI#1896]
As you make the screen smaller, there is an overlap from the left and the right side of the header. When you get even smaller, it changes to a hamburger view. We don’t want this overlap to occur, and should immediately becomes a hamburger menu. Picture shown below.
![image](https://user-images.githubusercontent.com/48491819/59048486-8bbf3700-884b-11e9-8a80-f5eb272e58b4.png)

In stage, we want to change what happens in the “in-between” view of this accordion toggle to immediately go to the full view. Each toggle should extend to the length of the screen/responsively. See below. 

![image](https://user-images.githubusercontent.com/48491819/59048554-ab565f80-884b-11e9-9843-76ddd180f8d9.png)

 Once that is fixed up, you might be able to tell that there is extra whitespace between the last accordion drop down and the document. (Shown below). Fix that up so there is less whitespace.

![image](https://user-images.githubusercontent.com/48491819/59048572-b90be500-884b-11e9-849b-e7e253163c56.png)

**Comment by annadebiasi** [comment]
MOBILE STAGE - Changed the accordion toggle so that the drop down menus do not collapse horizontally. Set the "Search Results Navigation" to have a fixed width. Made it so that it did not cut off document properties. Removed white space above document and below related objects drop down. Fixed header from collapsing too late.

CR - kgarelli, nquillin

revision number: 23064
