### ISSUE TITLE
OCMS Mobile Search

### ISSUE THREAD

**Issue by ebrent** [tsgrp/HPI#1897]
1. Adding a “pull out” tab to search (should be defaulted to pulled out so that you don’t see “no results” first thing)
- Tab between search and filters to filter out searches once a document has been searched on (filter tab will be defaulted when a search is made and search icon is hit again)
-Animation: when closing and opening, this should slide left and right and open as if you’re “pulling” although you only have to touch
-Good example of bootstrap pull out tab: https://codepen.io/Mindgames/pen/oxpzQd

2. Getting rid of slick grid and creating a different view for folders and documents
3. Thumbnail vs List View (Note the toggle button to switch views) - see below

![image](https://user-images.githubusercontent.com/48491819/59049361-6a5f4a80-884d-11e9-93fa-50ff355418e4.png)

-whats under linked “name” (Policy Contract.pdf) in list view should not be hardcoded values, these will come from the same values as slick grid, which order the client puts them in. 
![image](https://user-images.githubusercontent.com/48491819/59049449-97136200-884d-11e9-83a9-c8ecee241e2a.png)

3. Ability to run actions on document/folders
![image](https://user-images.githubusercontent.com/48491819/59049488-b4483080-884d-11e9-88c7-aca451b3b959.png)

4. unchecking/checking all (checkbox in same photo as above)

**Comment by annadebiasi** [comment]
MOBILE SEARCH - changed responsive grid with Bootstrap, so that it enhances the user experience in mobile/tablet view mode. This new list view is now able to be searched on and seen in view all document action as well. New SVG images and altered grunt file to accept these new icons as well

ENHANCEMENT CLOSED - https://github.com/tsgrp/HPI/issues/1897

CR - rsaladrigas, gsinger

Closed with revision #23370
