### ISSUE TITLE
BHUDI Selection Goes to Wrong Inputs when on Search Page

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1906]
![bhudi-issue](https://user-images.githubusercontent.com/547941/59531311-40d89b80-8eab-11e9-9db0-2c618cf907fa.gif)

**Comment by grahamsinger** [comment]
(Reserving for training)(

**Comment by astocks7** [comment]
INDEXER - indexing inside of the modal to fill out textboxes was sending the indexed values to textboxes outside of the modal if they contained the same id. Fixed by prepending 'this' to the jquery selector to correctly get the id from the current modal view.
OCMS revision #23770
CR - rsaladrigas, skovacinski

**Comment by astocks7** [comment]
INDEXER - similar to revision #23370, noticed that automatically moving to the next textbox after indexing was not working properly. Scoping the jquery selection properly solved the issue. updated unit test too.
OCMS revision #23779
CR - skovacinski, dvora
