### ISSUE TITLE
Positional data admin and capture not working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1930]
For reference, this is the configurations this issue is around:

![image](https://user-images.githubusercontent.com/1377228/62943976-4f570c80-bda1-11e9-9224-0ecc49cc83a7.png)

Issues (in priority order):

- [x] After fighting with the issues below and getting it correctly set to populate `hpi:metadataPositions`, the functionality isn't working at all in Bulk Upload.  I have the attribute set to visible for this testing, but nothing is populated.  After creating the object the node browser shows the value as `null`:

![image](https://user-images.githubusercontent.com/1377228/62945132-c097bf00-bda3-11e9-9fa7-afed087c9257.png)

- [x] Once you visit the Indexing Mode section in BU admin, save the config, and navigate away, if you navigate back it'll disappear completely.  The only way to get it back is to hard refresh.

![image](https://user-images.githubusercontent.com/1377228/62944051-7dd4e780-bda1-11e9-96ea-e4570fda56c5.png)

- [x] The dropdown should display attributes in the create form's (selected above in BU config) *first non-container* type.  It looks like, however, that the code is blindly selecting the first type in the form.  This means that in order to get the positional data functionality to work properly, you must have your document type ordered first in the BU form.  Additionally, it looks like the dropdown is displaying all attributes on the type rather than attributes in the form for the given type.  To summarize, the dropdown should target the first non-container type in the BU form, and then list attributes on the form for that type.

The above items should be tested and verified for the other areas of the admin that deal with positional data - Indexer Config and View Properties.

**Comment by CRdouglas** [comment]
INDEXER FIXES: Indexer now saves the correct json and passes this back to OpenContent. Generally cleaning up code associated with the original indexing commit.

- deleted unnecessary positionalAttrs js and html files
- added hpiMetadataPositions to hpi constants as a default for all projects using the indexer.js
- added metadataPositionAttr to the config-project for hpi-demo-alf, this defines the attribute used for housing positional data instead of picking from a dropdown in the config

CR - rsaladrigas, acastor

Rev: #23446

**Comment by gsteimer** [comment]
@CRdouglas re-opening this issue.  It seems to work now (with one document) in Bulk Upload, but still isn't saving positional data in the Indexer.  Tested on Edge2

**Comment by CRdouglas** [comment]
INDEXER FIXES: Indexer now saves the correct json and passes this back to OpenContent. Generally cleaning up code associated with the original indexing commit.

deleted unnecessary positionalAttrs js and html files
added hpiMetadataPositions to hpi constants as a default for all projects using the indexer.js
added metadataPositionAttr to the config-project for hpi-demo-alf, this defines the attribute used for housing positional data instead of picking from a dropdown in the config
CR - rsaladrigas, acastor

Re-Opened for config issues

Rev: #23446
