### ISSUE TITLE
Pagination broken in "View All Documents" and Search Results

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1942]
Next and Previous buttons aren't working...

![issueGif3](https://user-images.githubusercontent.com/4850976/64797989-ddace280-d547-11e9-8e76-accb7961279a.gif)

**Comment by astocks7** [comment]
VIEW ALL DOCUMENTS - pagination was broken because user preferences were being set to "list view" after the mobile update. Fixed by just never setting this preference because "list view" vs "table view" is dependent on the user's screen size, not their preference. Also wrote unit tests for multiple functions in searchresultcontrols.js
OCMS revision #23765
CR - skovacinski, rsaladrigas
