### ISSUE TITLE
Group Based AW Tasks Showing Up in Wrong Inbox Dashlet

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1947]
**Issue**
Not sure when this happened (will test on QA2), but AW group-based tasks are not showing up correctly in the AW Inbox.  Instead, the task is showing up in the Inbox, which is a different dashlet:

*Edge1 task in wrong dashlet*
![image](https://user-images.githubusercontent.com/1377228/65251910-bc0aa880-dabd-11e9-9885-ca5f13399957.png)

Acquiring the task from the Inbox dashlet on edge1, moves it to the AW inbox dashlet (only after refreshing), but interestingly, it keeps it in the group-based tab:

![image](https://user-images.githubusercontent.com/1377228/65252527-b82b5600-dabe-11e9-8ff5-e8c51ba4676a.png)

After clicking on the task or navigating to the form, it looks like the task is properly acquired:

![image](https://user-images.githubusercontent.com/1377228/65252846-46074100-dabf-11e9-8b3d-a718cdf0da62.png)

While this can be a workaround for demos, we need to fix this for a client deployment.  Especially for clients that _only_ use the AW Inbox.

There's two approaches we can take to fix this.  We should talk through this before going forward:

- Fix the issue as the dashlets are designed
- Bite the bullet and finally merge the two dashlets so we don't have two "inbox" type dashlets.  See #586 

Also - we're going to be merging in functionality to the AW Inbox soon.  This new functionality will enable pagination, sorting and filtering.  When implementing a fix for this issue, we should ensure that this new functionality works for both user tasks as well as group-based tasks.

**Comment by astocks7** [comment]
WIZARD INBOX - group based wizard tasks were not showing up in the ActiveWizard inbox, rather, they were showing up in the regular inbox. The task wasn't showing up in the AW inbox because whenever the assignee was null in getWizardTasks() in ActivitiClientWizardWorkflowImpl.java, it triggered an exception which skipped over the logic to add the task to the AW inbox. The fix to get the task into the AW inbox was to have a null check on the assignee there. 

To stop the task from also being routed to the regular inbox, I added some logic to filter out wizard tasks in ActivitiWorkflowImpl.java

OC revision 23760
CR: dvora, nquillin

**Comment by gsteimer** [comment]
Looks like there are still issues with AW group based tasks.  On edge2, I have a group based task routed:

![image](https://user-images.githubusercontent.com/1377228/68407990-21882680-014a-11ea-908c-c511172ca2eb.png)

However, when going to the stage, here's no way to acquire the task:
![image](https://user-images.githubusercontent.com/1377228/68408047-395faa80-014a-11ea-99bd-e93405dfc114.png)

Looking in the admin, the acquire task action is configured on the trac:
![image](https://user-images.githubusercontent.com/1377228/68408102-60b67780-014a-11ea-9d16-91d32e37e3bd.png)

**Comment by gsteimer** [comment]
Note - the acquire task action isn't showing up for non-AW group-based workflow tasks either:

![image](https://user-images.githubusercontent.com/1377228/68410145-df60e400-014d-11ea-90d5-edb2a976e201.png)

**Comment by astocks7** [comment]
AW ACQUIRE TASK - acquire action was not showing up for group-based wizard tasks in stage. Problem was they were incorrectly getting filtered out. Fixed by creating a new separate action for acquiring wizard workflow tasks and a new endpoint to get unclaimed wizard tasks in order to avoid the filtering issue. Also updated awworkflow.js to fix an outstanding issue where wizard tasks in the group inbox did not properly move over the individual wizard tasks after acquisition

OC revision 23790 | OCMS revision 24119
CR: nquillin, herzinger
