### ISSUE TITLE
Wizard Inbox Paginated Task Sorting Issue

### ISSUE THREAD

**Issue by nreiman** [tsgrp/HPI#1948]
**Note: You must have > 10 items in your AW Inbox to replicate this issue.
Upon sorting the AW Inbox and navigating to the next page, the way in which the collection is sorted is reversed. (If it's ASC it changes to DESC, and if it's DESC it changes to ASC.)
![AWPaginationSorting](https://user-images.githubusercontent.com/32136774/65282476-9d76d280-dafa-11e9-9d67-c0350728ac46.gif)

**Comment by ebrent** [comment]
There are a few other outstanding issues related to this pagination sorting issue due to the active/tab collections. 

1. On refresh, AW inbox shows your full collection instead of paging them (ex 10 per page, 20 per page, etc.)
![image](https://user-images.githubusercontent.com/48491819/68334341-095bcd00-00a0-11ea-87c7-4a45cdce96d7.png)

2. You have to click twice on the top of the column to sort on first load, then can click once after.

**Comment by ebrent** [comment]
3. Refresh doesn't work on dashlet either

**Comment by ebrent** [comment]
AW INBOX - Fixed pagination swap on next click, initial first load of only the 10 documents vs. all of the tasks loaded, and clicking twice at the top of the sorting column.

CR: rsaladrigas, nwoodbine
REVISION #24109
