### ISSUE TITLE
Saved Search updates not working when search config name doesn't match trac name

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1955]
Recently, updates went into OCMS that enable or disable public saved searches.  It looks like the functionality is working on Alfresco, but breaks on Documentum.  Here's what I'm seeing on edge1:

**Controlled docs search config**
![image](https://user-images.githubusercontent.com/1377228/66043852-e0b34700-e4e5-11e9-80b2-a3050e3677ee.png)

**Controlled Docs search -- Can create Saved Searches**
![image](https://user-images.githubusercontent.com/1377228/66044013-3982df80-e4e6-11e9-8daa-e2a347b0f8ca.png)

**User Prefs page -- saved searches do not show up**
![image](https://user-images.githubusercontent.com/1377228/66044048-4acbec00-e4e6-11e9-9c1f-1d845b644d03.png)

In the last screenshot, I should see the two saved searches I have in the controlled docs trac and be able to either delete or publish as a public saved search (since that is turned on in the admin).

This is breaking the search STS since it's trying to delete a saved search and cannot.

**Comment by engerernoah** [comment]
SAVED SEARCH ENABLE - Fixing issue #1955 where saved searches are not displayed in user preferences if the search config name doesn't match the trac name. This happened because we were using getSearchConfigForTrac which requires the names to match. To fix this issue we updated the code to use getSearchConfigByName. Updated the unit tests to reflect this change.

CR: skovacinski, acastor

revision #23781 - OCMS
