### ISSUE TITLE
Copy Form - Outstanding Items

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1961]
The following issues must be fixed for the Copy Form:

- [x] When copying a form, the code clears out questions that should not be populated on the new form.  For example, questions that are tied to a user input rule or supporting doc file input.  This clear works properly, however the page is not marked invalid when clearing out questions that are required.  Assuming the question is required, the page should be marked as invalid.  See screenshot below.  With the current functionality, a user can copy the form and complete it without answering all required questions.
- [x] The confirmation button UI should look like all other actions (buttons on the bottom right with a cancel button available)
- [x] The cofirmation message after copying a form is currently `Here is your copied form: ${formTemplateName}`.  At a minimum, we should be displaying the new form name, not the form template.  I'd suggest something like `Click here to manage your new form: ${newFormName}`.  Note that the copy form name only works properly when the form is autonumbered.

**After copy - question cleared, but page still marked as valid**
![image](https://user-images.githubusercontent.com/1377228/66311742-d245a080-e8d4-11e9-844e-29e50a91a6ce.png)

**Comment by ebrent** [comment]
COPY WIZARD FORM - fixed outstanding items such as: not refreshing the new form once copied in the background, , showing form's name as the clickable link instead of the form type, modal appearance, and workflow summary page to show that the form is incomplete if it cleared out supporting docs or user input questions. Biggest change was to change workflow relation to configurable parent/child relation via admin (dependent on alf or dctm). This required adding a custom config template. All items on issues https://github.com/tsgrp/HPI/issues/1961 and https://github.com/tsgrp/HPI/issues/1962. Updated test files to pass accordingly. 

CR: nwoodbine, aking

OC revision #23430
OCMS revision  #23846
