### ISSUE TITLE
Controlled Doc Obsolete for Documentum

### ISSUE THREAD

**Issue by henryerzinger** [tsgrp/HPI#1998]
Currently in Documentum, we do not have the functionality to handle document obsoletion.  The purpose of this enhancement will be to have an OC job that queries for controlled documents in the approved or effective state and have an obsolete date set to before the time of the  job running.

**Comment by benallenallen** [comment]
Shouldn't be limited to just Documentum... this job should be agnostic to which repo it is on so that it would work in HBase as well.

Also, i think what you are looking for already exists:
"/aw-job/makeDocsObsolete" in RESTWizardJobs executes Wizard2Impl#makeDocsObsolete

Just needs a way to be scheduled, and it should be good to go @henryerzinger

**Comment by gsteimer** [comment]
@benallenallen - this new job is in the broader "OC Jobs" framework and I'd like to get away from using those "AW Jobs" (and the old Alfresco script jobs eventually).  This new job should be agnostic but the Gritty project is going to test Documentum only.  At some point we should verify this against Hbase and Alfresco and remove their respective obsolete mechanisms. 

@henryerzinger - Ben is correct though that you can just use `Wizard2Impl#makeDocsObsolete`.  We shouldn't be duplicating that code.

**Comment by astocks7** [comment]
OC JOB FOR OBSOLETE DOCUMENT - created an OC job action that runs every half-hour and queries on all effective/approved aw controlled docs that have an obsoletion date that has passed. After retrieving the docs from the query it sets the status of all of these docs to Obsolete.

OC rev 23864
CR: gsteimer, nquillin
