### ISSUE TITLE
When more than one signature role is triggered, the last role does not have signature applied

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2013]
See the screenshots below.  If I only route to the `CR Approval` task, the signature is correctly applied to the sig page.

Edge2 - One role:
![image](https://user-images.githubusercontent.com/1377228/70555150-1b6bd800-1b44-11ea-8058-63caaf402763.png)

However, if I have both `Initial QA` and `CR Approval`, the latter task does not appear on the signature page at all:

Edge2 - two roles:
![image](https://user-images.githubusercontent.com/1377228/70554779-65a08980-1b43-11ea-9f4e-3eeaf754dd6c.png)

**Comment by gsteimer** [comment]
For now, we're going to close this one by adding a "don't refresh the sig page after final approval" switch that alfresco will use.  All signatures will appear on the page, but the version listed will be the minor version vs. the major.

**Comment by mwojno-tsg** [comment]
This issue is closed by the commit 24112 in OC. A temporary fix was implemented to toggle off the regeneration of the signature page once the psi is promoted to approved. Another issue (https://github.com/tsgrp/HPI/issues/2014) was created to keep track of the larger issue at hand here, which is the approval details are not successfully communicated between listeners.
