### ISSUE TITLE
Signature Page for Documents has Null username

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2022]
Note - I tried to replicate this on edge2 and release2, but cannot due to #2021 

On the QA2 environment, when I sign off on a form with attached documents, the signature page looks fine for the form:

![image](https://user-images.githubusercontent.com/1377228/71215366-237ef280-227d-11ea-9241-675411076916.png)

However, the signature for the documents has a `null` user:

![image](https://user-images.githubusercontent.com/1377228/71215390-32fe3b80-227d-11ea-929a-aae324f6655e.png)

This is the form in question: https://qa2.tsgrp.com/ocms/Stage/wizard/workspace://SpacesStore/36c99a40-2d2e-42a0-8f27-19054fc568be%2Bcurrent%7Cworkspace://SpacesStore/36c99a40-2d2e-42a0-8f27-19054fc568be%2Bcurrent

**Comment by gsteimer** [comment]
note - tested again and this is happening for all signatures (during the route as well - not just when the form is approved)

**Comment by astocks7** [comment]
WIZARD FORM ATTACHED DOCS SIGNATURE PAGE - The username for the signatures on attached documents has been showing up null; turns out it was never being set on the doc signatures in the first place. Fixed by applying the username to each doc signature just as we do for the form signature and refactored that logic out in WizardWorkflowHelper

OC rev 24213
CR: dgrumieaux, nwoodbine
