### ISSUE TITLE
Create New Folder - Uniqueness check on computed field not working properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2028]
See the screenshots below.  When using the "Attribute is Unique" rule on a normal text field in the create new folder form, it correctly validates and displays the banner at the bottom that allows the user to navigate to the existing folder:

![image](https://user-images.githubusercontent.com/1377228/71747089-5ce65f00-2e34-11ea-880d-360f35f9a2e1.png)

However, on the underwriting trac, we have the "Attribute is Unique" rule on a computed, since policies in our environment are unique based on two properties (policy number and year).  In the screenshot below, the user correctly cannot create an existing policy, but interestingly the bottom banner does not appear at all:

![image](https://user-images.githubusercontent.com/1377228/71747185-9fa83700-2e34-11ea-85a6-b82164785b40.png)

**Comment by nquillin91** [comment]
The functionality to check for folder existence is based on the attribute that is configured as unique using external rules. In the external rules there is a configuration option  to "Clear Invalid Selected Values". See below.

![image](https://user-images.githubusercontent.com/13734523/71748719-04fe2700-2e39-11ea-97a9-ee70a616f0b1.png)

This configuration was turned on and was messing with the existence validation logic. That option should not be configured for the attribute being used for the folder existence check. Once it was turned off, the issue was resolved.
