### ISSUE TITLE
Filter By Facet Popover Not Rendering Properly

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2030]
## Description
In the stage table view, the filter by facets popover is improperly rendering when clicked multiple times or switching display views. See attached gif.
![facet filter popover](https://user-images.githubusercontent.com/54869173/71989897-1740e200-31f8-11ea-9c78-34451c4e348d.gif)

**Comment by abrown45** [comment]
### Findings
I found the popover is being built and instantly being destroyed in the above scenario. You can see the div flicker on the DOM. I suggest looking into how the popover is being created and destroyed and how the popover is being destroyed when clicking outside the div.

**Comment by jlittle-tsg** [comment]
FACET FILTER POPOVER BUG - fix for issue https://github.com/tsgrp/HPI/issues/2030. The search results stats and filter by facet popovers had click listeners that were conflicting with one another. Gave them both a generic class and use that as the jquery selector so that they will share one listener.

CR: cdouglas, dvora
Revision Number: 24552
