### ISSUE TITLE
Search Results Timing - "Other OCMS Time" is being recalculated

### ISSUE THREAD

**Issue by Swence32** [tsgrp/HPI#2032]
In the **View All Documents** action on edge2, the search results timing appears above the search results table. Clicking the icon shows the specific timings for different portions of the loading process, including "Other OCMS Time".

When one of the following steps are performed, the "Other OCMS Time" is reevaluated and the overall timing changes. This is reflected both in the results in the timing dropdown, and in the status color of the icon:

- [x] Resize the window
- [x] Choose a predefined filter that would alter results in the table
- [x] Perform facet filtering
- [x] Enable standardized table view
- [x] Reset tableview to defaults

![SearchResultTiming](https://user-images.githubusercontent.com/5685648/72169736-49d41180-3395-11ea-8f00-ec6f38b34aa1.gif)

**Comment by jlittle-tsg** [comment]
SEARCH RESULTS TIMING BUG - fix for issue https://github.com/tsgrp/HPI/issues/2032. Now initializing the SearchStatisticsView in searchresultcontrols.js because it was getting re-rendered when a search wasn't actually performed. Also added in Boolean that is marked when a ocquery is executed to tell us so.

CR: cdouglas, gsinger
Revision Number: 24555
