### ISSUE TITLE
Search criteria form clears out values after searching when using Remember Last Search Term

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2056]
When I have a form set to have a field "Remember Last Search Term":

![image](https://user-images.githubusercontent.com/1377228/74249897-7b4f3e00-4caf-11ea-92d2-30b850e435db.png)

The search will clear out other criteria values after executing the search:

![search-form-clearing](https://user-images.githubusercontent.com/1377228/74249947-8a35f080-4caf-11ea-8b22-723268e492fd.gif)

The search is returning the correct results, but for some reason the `SCR` portion of the search results is cleared out.  While I don't think the fix for #2040 caused this issue, it's a good place to start since that issue is very similar.  It's basically the opposite of this one.

Note that for this issue, I can recreate it whether or not saved search is enabled.  #2040 seemed to only occur when saved search was disabled.

**Comment by gsteimer** [comment]
Update - on both edge1 and edge2, @engerernoah found that search blanks out on a simple refresh on all tracs

**Comment by engerernoah** [comment]
The issue appears to be in attributeSearch#setAdvSearchParams, this method takes in a query which is used to set the form values with the search parameters. This function then checks if there are any cookie values for remember last search term. The issue is, if there is a field with remember last search term then setValues is called again. The first thing setValues does is clear out the form values so when we have values on both the cookie and the query only the cookie values are populated. An update to this method would need to be made to only call setValues once and to build up one object with both the query and the cookie values to pass into setValues.

**Comment by nreiman** [comment]
OCMS Revision: 24851
CR: nquillin, dvora
