### ISSUE TITLE
Refreshing the Search Screen Causes Search Criteria to Blank Out

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2057]
On edge1 and edge2 (but for some reason not on edge3), if you refresh the browser while on the search screen, the search criteria will blank out.  See screencam below:

![search-blankout](https://user-images.githubusercontent.com/1377228/74252948-0d594580-4cb4-11ea-92b7-5a4ed213eea8.gif)

**Comment by abrown45** [comment]
### Findings
* Missing views: AttributeSearch.View, AdvancedSearch.LayoutView, FacetSearch.View*
* Occurs on Refresh not through "back" navigation
* The initialize for SearchSidebar.Views.Tabs is not executing

**Comment by abrown45** [comment]
[Duplicate Issue](https://github.com/tsgrp/HPI/issues/2068)

**Comment by engerernoah** [comment]
SEARCH NOT RENDERING ON REFRESH - Fixing github issue: https://github.com/tsgrp/HPI/issues/2057

Recent updates went into search sidebar to stop multiple renders from triggering code numerous time. This created a timing issue that caused searchSidebar to not render completely. We refactored the sidebar to handle more of its logic within the initialize instead of on beforeRender each time. We then added deferreds around the initialization of some of the subviews to ensure everything is set up before we render the sidebar. This allows us to only render the sidebar and all of its subviews once which fixes issues with the form showing twice and listeners being wired up more than once, while fixing the timing issues that caused the sidebar to render before all of the subviews were created. 

Additionally while working through this issue we updated the formatting in the attributesearch.js file be more consistent in order to enhance the readability. The only logic changes to attribute search were adding calls to stopListening() before wiring up our listeners just as good practice cleanup to safeguard against multiple listeners triggering in the future. These logic changes are on lines: 258 and 341

Unit tests were updated in searchSidebar to reflect the changes made, unit tests were not added to attributeSearch due to time constraints as the after render method would likely need to be refactored/ broken out to easily unit test. 

Revision: #24827

CR: jhof, rsaladrigas
