### ISSUE TITLE
Collections page does not load

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2067]
On both edge1 and edge2, the collections page is not loading properly.  On edge2, the console and network tabs show no errors and there are no errors in OC.  The query to return collections seems to be fine:

Edge2:
![image](https://user-images.githubusercontent.com/1377228/74745836-1a34e680-522a-11ea-9071-341c99d10be7.png)

However, on edge1, an error does occur:
![image](https://user-images.githubusercontent.com/1377228/74745930-3cc6ff80-522a-11ea-8cf8-d8c1092fea29.png)

Collections worked properly as of the STS run on Monday 2/10.  Something must've changed to break collections between Tuesday 2/11 and Sunday 2/16.

**Comment by engerernoah** [comment]
COLLECTIONS PAGE DOES NOT LOAD - The collectionsidebar.js file used the searchsidebar-tabs template which was updated to be specific to searchSidebar. This caused the collections page to break divs were no longer being properly set. This update creates a collectionsidebar-tabs.html to be used as the template for collectionSidebar and models the format of searchSidebar. 

A skeleton unit test file was added since collectionsidebar.js did not have a spec file before. Actual unit tests were not added due to time constraints. 

Revision: #24828

CR: rsaladrigas, jhof
