### ISSUE TITLE
Improve Date and Autocomplete Validation

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2079]
When loading a form, validation fires for date fields and autocompletes even before the user interacts with the fields and when the field is not required.  Ideally, the red text would only appear after the user attempts to interact with the field, similar to how textbox validation works.

Some examples:
Edge2 Create Vendor:
![image](https://user-images.githubusercontent.com/1377228/75726848-061cca80-5ca9-11ea-9919-24cdfa7611a2.png)

Edge2 View Claim Props:
![image](https://user-images.githubusercontent.com/1377228/75726942-51cf7400-5ca9-11ea-8a21-44891e349571.png)

Edge2 View Controlled Docs Props (Note that the fields are disabled and not required):
![image](https://user-images.githubusercontent.com/1377228/75727077-aa9f0c80-5ca9-11ea-99aa-1168a72cae6d.png)

Edge2 Start Workflow (non-OTC form, date field is not required):
![image](https://user-images.githubusercontent.com/1377228/75726975-70356f80-5ca9-11ea-8359-c739deef6e1e.png)

Autocomplete vs. Textbox Validation:
![validation-fail](https://user-images.githubusercontent.com/1377228/75727274-344eda00-5caa-11ea-91a0-e6a57625558d.gif)

**Comment by joehof** [comment]
Fixed with OCMS commit 25026.

Form support was validating picklists and dates before we ever had a chance to set any values to them, which is not the desired behavior. The biggest offender was default value code setting blank values to picklists, which then kicked off knockout value.subscribe, which then hit validation. Added logic to only set values when there is a value to set.
