### ISSUE TITLE
Doc Viewer: Action Container Rendering Improperly

### ISSUE THREAD

**Issue by abrown45** [tsgrp/HPI#2091]
### Issue
Opening View all Documents and clicking on a document link causes the action container to render improperly.

#### Key Points
My intuition is that this is a timing issue. If you quickly navigate to the doc viewer the issue is shown, otherwise the container renders as expected.
This issue is also very difficult to recreate. I have seen it many times over the past few month but have not pinpointed an easy way to get it to appear, another reason why I feel it is timing related.

#### Preview
![image](https://user-images.githubusercontent.com/54869173/77563116-db302b80-6e8e-11ea-80b2-dec5b4faabea.png)

**Comment by gsteimer** [comment]
Bumping the priority of this since I think it's something we should look at sooner rather than later.  I've also noticed this a number of times.  There's code that attempts to check the width of the action area and figure out where the "more" button should come in.  As @abrown45 mentions, it's likely a timing issue.

**Comment by abrown45** [comment]
Found an additional issue might be the same fix. Opening doc viewer in full pane -> opening view properties as a non-modal view -> closing the view properties window results in the doc viewer header being two lines. 
![view properties](https://user-images.githubusercontent.com/54869173/77581412-9ff02580-6eab-11ea-817d-7ebaefe6a623.gif)

**Comment by mwojno-tsg** [comment]
To reproduce this issue more frequently `Empty Cache and Hard Reload`. Then, open the doc viewer in dual panes

**Comment by mwojno-tsg** [comment]
This issue was resolved (for now) in commit #25137. I say for now because this is a timing issue and the fix was to modify the `_throttle` to have an increased wait time that surrounded the `resizeHeader` function in `docviewer.js`. If any more logic is added to the resizeHeader it could throw off the timing again. That was not the scope of this issue fix as it would be a re-work of `docviewer.js` re-sizing capabilites and timing. 

Couldn't produce the second issue. Going to assume it was either fixed or it isn't an issue anymore
