### ISSUE TITLE
Search fails in IE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2148]
The timeline commit added some code that breaks in IE:

```javascript
var searchConfigTypeModel = self.searchConfig.get("resultsConfig").get("resultsTableConfig").get("types").models.find(function(model) {
                    return model.get("objectType") === objType;
                });
```

The error is:

```
SCRIPT438: Object doesn't support property or method 'find'
```

**Comment by engerernoah** [comment]
Fixed in Revision #25445

TIMELINE VIEW - Fixed some issues found with revision 25439 and updated some logic and styling for demo purposes. This commit (like 25439) will be re-visited for some cleanup and unit tests

Problems fixed:
-Words over flowing the timeline popover
-Doc viewers name would sometimes appear in the iframe
-Fixed a few places using .find rather then underscores find (breaks IE)

Additions:
-Added noImageFound png's for dicom and videos
-Timeline documents are now sorted down to day rather then just month
-Re-added the no-Image png for documents

CR: ballen, iwhiting, nengner
