### ISSUE TITLE
Form Support Help Text Issue

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2154]
## Overview
- The help text for the form config through OCMS admin seems to be clearing whatever is typed once it loses focus of the screen instead of saving the help text. Therefore, not allowing a user to use the Help Text functionality. 

## Steps to Reproduce
- Head to OCMS admin, then the Forms section. Choose any form. Have an attribute and click on the Options dropdown. Try to fill out the Help Text text area. It won't save and will be cleared once focus is lost.

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/54864662/87178581-f9d1fb00-c2a2-11ea-90c6-920b1d91885f.gif)

## Insight into Possible Solution
- After digging through `formsupport.js` and `formattribute.js` , it appears that the `that.helpText` is observed and set on the model but nothing is done with it within these files.

- Therefore, the course of action should be to either disable for the time being so we don't deceive users and or provide an implementation for this help text functionality.

**Comment by jackjbridge** [comment]
FORM SUPPORT HELP TEXT: Fixing issue with help text not persisting in the form config, or being displayed on forms. Issue revolved around html being parsed on the first dash and ID had an extra dash added to the name, causing the wrong attribute value to be updated. Also making tooltips in formsupport.html the bootstrap tooltip.

NOTE: Not writing unit tests for one-line addition in formsupport.js due to difficulty testing formsupport (approved by Rene and George)

SVN: 25532

CR: rsaladrigas, nengerer
