### ISSUE TITLE
Approver List does not update properly if Form is routed for approval and then cancelled or rejected

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2164]
Steps to recreate:

1. Create a wizard form and assign approvers.  The approver list (visible using the workflow status action, will show the correct approver list): 

![image](https://user-images.githubusercontent.com/1377228/87583402-8284d880-c6a1-11ea-95ac-d4dd033e1c9f.png)

![image](https://user-images.githubusercontent.com/1377228/87583441-8fa1c780-c6a1-11ea-984d-fbe3b28f0c70.png)

2. Edit the form and add more approvers.  This will work fine:

![image](https://user-images.githubusercontent.com/1377228/87726045-ed0e4500-c783-11ea-82f4-adf19a5c53dd.png)

![image](https://user-images.githubusercontent.com/1377228/87726082-f8fa0700-c783-11ea-83a1-48df59d5c39e.png)

3. Start a workflow approval route.  Immediately cancel the route
4. After the form is back in the Draft state, add another approver.  This time, the list or approvers will **NOT** include the added approver:

![image](https://user-images.githubusercontent.com/1377228/87726215-31014a00-c784-11ea-9cbf-82184570729f.png)

![image](https://user-images.githubusercontent.com/1377228/87726229-39598500-c784-11ea-85cc-154ddfd1d0d3.png)

In this last screenshot, `Jim Halpert` should have been included in the list.  If I were to start the workflow, Jim would not get a task.

To work around the issue, you need to delete the Approval Details json, and then it'll start working again.

**Comment by gsteimer** [comment]
Verified that this is a problem on both edge1 and edge2

**Comment by mwojno-tsg** [comment]
Closed with OC commit: 25745. 

This commit was a result of the commit #25614 where an in-memory cache for the approval details was implemented. What happens when the approval details are modified (a relationship or association is modified which causes approval details to change) the changes do not get reflected with the cached approval details. This commit puts in place a re-generation mechanism that will happen whenever a relationship or association is changed. This tells us that the approval details in the repo and in-memory cache need to be synced up. The re-generation function was created in WizardHelper and used in the FinishAndSubmitPSIActionExecutor.java (creating or editing form) and ManageRelationsActionExecuter.java (attaching new workflow document). 

CR: aking, dgrumieaux
