### ISSUE TITLE
OTC and NMAC Config lists repeating attributes as single valued

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2167]
See the screnshot below.  On the new Distribution Lists aspect, there are two repeating attributes.  However, the NMAC config lists them as single valued:

![image](https://user-images.githubusercontent.com/1377228/87985266-e8f26800-caa0-11ea-9d78-e425f8eb3106.png)

**Comment by gsteimer** [comment]
Updated issue title since this seems to be a problem with OTC as well.  For example:

![image](https://user-images.githubusercontent.com/1377228/88059293-45e63080-cb2a-11ea-87f0-d2480cd6b582.png)

Folder Tags are repeating.

**Comment by astocks7** [comment]
OTC AND NMAC CONFIG: The display value of "repeating" in OCMS admin for both the OTC and NMAC has been displayed as "false" for all attributes, including repeating attributes. Tweaked the data-bind in both nonmandatoryaspectconfigattrs.html and hpitypeconfigattrs.html so that we correctly grab the value of "repeating" so that it displays "true" for repeating attributes.

OCMS REV #25586
CR: aking, kgarelli

**Comment by gsteimer** [comment]
On edge2 I still see the wrong value for `Repeating`, both in OTC and in NMAC:

![image](https://user-images.githubusercontent.com/1377228/89330939-92675b00-d656-11ea-82d9-bcb92b0c4727.png)

Claim Doc OTC:
![image](https://user-images.githubusercontent.com/1377228/89330987-a7dc8500-d656-11ea-8fbb-9eef31ecbd3f.png)

Interestingly enough, a few of the OTC types are correct.  For example, Car Auction Document:
![image](https://user-images.githubusercontent.com/1377228/89331053-c2aef980-d656-11ea-98c8-619f2c0536e5.png)

**Comment by astocks7** [comment]
Looks like on edge1 and edge2 the attrs which are currently mislabeled will need to be removed/readded to see the fix. Removing/readding attrs should be safe but just in case we will back up the edge configs before making any changes

**Comment by gsteimer** [comment]
Looks like this is still a problem.  I added the new non-mandatory aspect for subscription attrs, and the user list repeating attribute is showing as non-repeating:

![image](https://user-images.githubusercontent.com/1377228/93106817-6805b600-f676-11ea-9bf4-628fcd4adc45.png)

**Comment by engerernoah** [comment]
NMAC Config LISTS REPEATING ATTRIBUTES AS SINGLE VALUED - fixed with OCMS revision: 26547
When adding a new NMAC in the admin configs if there was an attribute with repeating values the config would be added with repeating set to false. This was due to the build up of the singlenonmandatoryaspect view not including the repeating property when pushing to the collection. The fix was just to make sure we added that property when pushing to the collection. Commit includes some cleanup/refactoring to aid unit tests and includes unit tests around the code we updated. 

An additional commit to follow to update unit tests that didn't pass based on time zone differences. 

CR: skovacinski, kgarelli
