### ISSUE TITLE
Form Support Help Text cuts off in dual pane view

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2178]
With the fix for #2154 , help text now appears in form support if configured.  However, depending on the size of the text, if it expands beyond the pane that the form is loaded into (ex: dual pane view with a doc in the stage), the help text can appear behind the other pane.  For example:

![image](https://user-images.githubusercontent.com/1377228/88550326-11212000-cfe7-11ea-94ce-c586dc3efaac.png)

The full text should be:

> Groups selected here will receive a notification when this document is Approved, Effective and Obsolete

**Comment by gsteimer** [comment]
@dgrumieaux @jackjbridge - looks like this is a problem for modal actions as well:

![image](https://user-images.githubusercontent.com/1377228/88551180-2ea2b980-cfe8-11ea-9d66-6200392a476b.png)

The text is getting pushed behind the form control on the right side.

**Comment by jackjbridge** [comment]
FORM SUPPORT BOOTSTRAP TOOLTIPS: Fixing bootstrap tooltip information being cut off in some use-cases with form support. This issue has been fixed by making the data-container the body for tooltips in form support. More information about the fix can be found here: https://stackoverflow.com/questions/32287914/tooltips-cutoff-in-container

SVN: 25541

CR: aking, dgrumieaux

**Comment by jackjbridge** [comment]
Just a knowledge dump from when I tried to wrap text for formsupport: This became difficult for a few reasons:

In the commit above, we prevent cut-off by having the tooltip container injected in the body...this prevents from specifying CSS on the form support specific tooltip elements to set up wrapping. However, in a different style file we seem to unintentionally set up styling for all tooltips(that aren't overwritten with a more specific styling) that prevents text-wrapping. A solution I tried, was making the container the form support class. This allowed me to apply styling to these specific tooltips. The problem here was that the form support container size seems to differ based on whether it's used in search or an action modal, etc. Going forward, if we'd like to implement text wrapping for these tooltips we would need to find a consistent container size for them to be placed in
