### ISSUE TITLE
Create New Folder Action Fails to load form if more than one folder type is configured for a trac

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2188]
If a trac configured for the Create New Folder action has more than one folder type, it will fail to load the form.  For example:

![create-folder-fail](https://user-images.githubusercontent.com/1377228/88706728-da2a3780-d0d6-11ea-8497-23d1d42906d3.gif)

On edge2, the affected tracs are: Engineering, Contract Management, and Incident.  This issue is seen on both edge and release, but works in QA2, which is running the 3.4 release tag.

**Comment by abrown45** [comment]
Because of how `self.securityByPathSuccess(objectType, resolvedObjects, numTypePaths, true);` is called in createFolder.js, the variables passed to this function are "passed by value" in a sense rather than "passed by reference". I belive updating this function to pass in a json object with resolved, and numType properties would resolve this issue.

**Comment by cheinz-tsg** [comment]
Closed with ACA Commit #25564. 

There was some deferred logic that was supposed to run when all object types configured for the trac were processed, but due to a bug this logic wasn't always executed. Restructured the deferred logic to avoid this in the future.
