### ISSUE TITLE
Notifications - long text cut off and no way to view without sorting table

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2189]
Notifications with long text are correctly cut off so the table row only takes up one line.  However, see the screencam below - the `i` icon to view the rest of the notification doesn't show up until the user sorts the table:

![notification-view-fail](https://user-images.githubusercontent.com/1377228/88822672-c4297f00-d189-11ea-9c44-f4ce5206f448.gif)

While we're in here - should we make it easier to see the expanded text?  It's not intuitive to have the user click the `i` icon.

Thoughts @iwhitingTSG ?

**Comment by nreiman** [comment]
Thinking this has something to do w/ rendering...
- If you click on "My Notifications" or "Archived Notifications" once the modal has loaded, the `i` icons also appear as expected.
- If you type something into the filter, the `i` icons also appear as expected.

In the afterRender, I added this logic...`if(messageHTML[0] && (messageHTML[0].offsetWidth < messageHTML[0].scrollWidth)) {...}`. Before the modal has loaded, both messageHTML[0].offsetWidth and messageHTML[0].scrollWidth are 0. Though, once the modal has loaded on the screen and you do an inspect on the elements, the values are populated. 

Things I've tried that aren't working: 
- Moved the `afterRender` to the other views
- Called `this.notificationViewLayout.render();` in the afterRender after the `_.each` (assumed it would result in an endless render loop..but thought I'd try it)
- Using 'clientWidth' instead of offsetWidth/scrollWidth
- Updating notifications.styl `.display` to have `white-space: nowrap` (also tried removing it from tr > td)
- Updating handlebars {{#unless showViewExtraDetailsIcon}} to be an if, and updated logic for showViewExtraDetailsIcon
- Tried doing something like this in the main view: 
```
if(!this.isDashlet)	{
     $("#notificationModal").on('show.bs.modal', function () {
         //_.each logic here
     }).modal('show');
```

**Comment by jlittle-tsg** [comment]
Fixed with OCMS Revision 25732

-----
NOTIFICATION ICON RENDERING - fix for issue https://github.com/tsgrp/HPI/issues/2189. Adding a deferred to notificationsview that will get resolved when the modal has loaded to ensure that the notification html has been rendered on the DOM. If the notificationview.js is launched in a dashlet, the deferred will get resolved right away.

Also added some styling to the message col of the view to wrap long words.

CRs: jhof, rsaladrigas
