### ISSUE TITLE
Advanced Combine to PDF unable to load in stage when Enable Users To Customize Bookmarks is configured

### ISSUE THREAD

**Issue by jackjbridge** [tsgrp/HPI#2199]
There appears to be a javascript error in formsupport, when we try to launch Advanced Combine to PDF in stage and the Enable Users To Customize Bookmarks is on. For some reason, self is defined as a bookmark column, as opposed to the window like it is for other runs through the formsupport afterRender function. Ex: 
![image](https://user-images.githubusercontent.com/42980355/89313651-63dd8600-d63e-11ea-9643-445e5cd5a637.png)

What the error looks like:
![image](https://user-images.githubusercontent.com/42980355/89313733-7fe12780-d63e-11ea-889c-1797f00967e1.png)

**Comment by abrown45** [comment]
The issue is because within the slick.bookmarkcolumn the global self is modified rather than than a local version. Not sure what the scope of self should be or if some fancy logic is being attempted for bookmarking, it does not appear for other column plugins. It does produce a linting error. Should be as easy as replacing `self = this;` to `var self = this;`

**Comment by Kovacinski** [comment]
This fix shouldnt just address the slick.bookmarkcolumn's global self but should also fix formsupports use of a self that it never defines

**Comment by jackjbridge** [comment]
FORM SUPPORT TOOLTIP: Fixing two things: First I am fixing formsupport using a self context it does not define itself when activating the bootstrap tooltips (broken in SVN commit 25532). Second I am fixing slick.bookmarkcolumn.js modifying the global self. This situation was causing Advanced Combine to PDF to break when bookmarks were configured.

SVN: 25657

CR: skovacinski, abrown
