### ISSUE TITLE
AW Answer Justification Validation Not Working Properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2246]
See the screencam below.  When I enter answer justification, the validation doesn't recognize that the value is populated.  Instead, I need to click on the "Other" answer again to get it to register.

![aw-answer-justification-validation](https://user-images.githubusercontent.com/1377228/91314904-aea17800-e77c-11ea-933d-257cafff1799.gif)

**Comment by mwojno-tsg** [comment]
This issue is closed with OCMS commit: **25859**. 

- The issue fix was within the `field.js` file. Essentially, `options` can be undefined when it goes into the `Field` function and there was a check for an attribute on there. 

- However, if `options` is undefined it will fail and not execute the rest of the invalid/valid logic below. Null check added and resolved issue. Unit test file created. 

CR: aking, gsinger
