### ISSUE TITLE
Cannot see long entries in autocomplete with narrow screen

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#2256]
See below image for example

This appears to be due to us setting the width of the list element equal to the parent width with the following code:

`var parentWidth = $(that.$el).parents(".typeahead-group").width();
                                $(".typeahead-dropdown").css({ "width": parentWidth });`

![image](https://user-images.githubusercontent.com/547941/91903401-cf7c3880-ec68-11ea-8dce-bcc4f05d6a96.png)

**Comment by mwojno-tsg** [comment]
Issue closed with OCMS commit number: **25852**. 

A small modification was made to `formsupport` where it was dynamically setting the `.css width` so that each dropdown was the same size. However, this issue identifies the edge case that if it is bigger than the width it gets cut off. `width` was changed to `min-width` to account for that edge case overflow. 

CR: jhof, iwhiting
