### ISSUE TITLE
Review Comments Document not Allowed to Upload

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2345]
See the screenshots below.  I do not have any restricted file types in the admin:

![image](https://user-images.githubusercontent.com/1377228/102134729-8ec1bd00-3e1c-11eb-9824-b74d0930a02c.png)

However, when attempting to upload a document the interface does not accept a PDF:

![image](https://user-images.githubusercontent.com/1377228/102134829-ad27b880-3e1c-11eb-8360-4be10837c223.png)

Even if I update the admin to only accept `pdf,docx,doc,xlsx,xls`, the same thing happens upon document upload.

**Comment by gsteimer** [comment]
It seems that in this action, file types need a dot.  So for example: `.pdf,.docx`.  While we're in here, we should also remove the need for the dot to be more consistent with Bulk Upload.  For example, on the insurance tracs, the whitelist type config is:

```
pdf,jpeg,jpg,png,gif,doc,docx,docm,msg,potm,potx,ppsm,ppsx,ppt,pptx,pub,xls,xlsx,xlsb,xlsm,xltm,xltx,xltx,xps,html,mp3,mp4,txt,xml,json,eml,zip
```

**Comment by abrown45** [comment]
Somewhere the `approvedFileExtensions` variable is adding a unicode character to the string so blank is actually a length greater than 0. Fix should account for this with a different way to check and an additional unit test to cover this case.

**Comment by abrown45** [comment]
Steve is suggesting finding the root cause so in case other places are also adding the character

**Comment by abrown45** [comment]
Closed with commit 26204
DRAGDROPTOUPLOAD FIX AND ENHANCEMENT - fixing an issue caused by an empty string of approvedFileExtensions, it now correctly allows all files when blank. Enhanced the approvedFileExtensions list to match bulk upload by allowing a comma separated list of file extensions that could include periods or spaces but doesn't require it. Updated unit tests.
GH: https://github.com/tsgrp/HPI/issues/2345

CR: rsaladrigas, nreiman
