### ISSUE TITLE
TextArea Broken

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#237]
As soon as I configure an input to be a "Text Area" in the admin, advanced search doesn't render anymore and view properties doesn't work either. Seems to be something with the new admin settings for "Is Timestamped" or "Only allow new entries"

![image](https://cloud.githubusercontent.com/assets/4850976/2735957/d33bfee4-c666-11e3-96b8-5b2da62add34.png)

![image](https://cloud.githubusercontent.com/assets/4850976/2735967/f89daaca-c666-11e3-9f92-cf974e41474d.png)

![image](https://cloud.githubusercontent.com/assets/4850976/2735938/82df36be-c666-11e3-8dd3-cb4741bef221.png)

**Comment by joehof** [comment]
TextArea was completely thrown out of whack by the upgrade to newer bootstrap.

The TextArea control now only works for a single valued attribute and has been updated to use the max/min length validation that the TextBox attribute uses.

A new control called TextAreaList has been created, that only works for repeating attributes, which acts just like the old "Multiple Text Area" from before. 

Fixed with HPI update #12599
