### ISSUE TITLE
Complex Form's JSON Rendition Invalid After Publish in Alfresco 7 in ACA PnP

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/hpi#2430]
## Overview
- This is an interesting that popped up in a customer's environment who was recently upgraded to Alfresco 7. The issue appears to have been found after a change was executed on the e-form within the WizardAdmin. To apply the change in the environment, a publish page set needs to be made and that appears to where the issue happened. 

- If you aren't familiar, the publish in WizardAdmin will create a JSON rendition of the xml pageset. It appears the JSON that is created is valid but has some issues within it because there are errors encountered on the OCMS side when a user tries to create a new form. 

- Another important detail is that the Change Request form that is deployed by default in the ACA PnP environments does not encounter this issue. So, that is why this edge case issue was not caught in our testing when upgrading to Alfresco 7. It appears this issue happens on complex forms. The form I tested has 140+ pages and a complex page flow with multiple queries. 

## Steps to Reproduce
- I replicated this issue by using the alfresco installer to install Alfresco 7 locally. I then used the PSA tool to upload the complex form to the environment. 
- I published the form through the PSA, but also tried publishing within the WizardAdmin. Both publishes will yield the same result.
- After publishing, simply try to create the new form. You will notice the issue happens after the `/content/content` call where it grabs the JSON rendition of the form to then parse on the OCMS side. Here is the errors you will receive in the browser.

![image](https://user-images.githubusercontent.com/54864662/127877142-2d533987-b17b-49a6-9af4-d4a0b75eacaa.png)

## Thoughts About Issue
- One key change that happened during the upgrade to Alfresco 7 was the change in what json .jar was being used. We went from using `json-20090211.jar` to using `json-20200518.jar`. See: https://github.com/tsgrp/HPI/issues/2363. We fixed a few areas within OC that were breaking as a result. This change will be a great starting point to investigate a little more on what exactly changed. 
- I say to investigate the json jar change because the part in code that actually performs the transformation is in PSIUtil where the XML class it `org.json.XML`.
![image](https://user-images.githubusercontent.com/54864662/127877666-e1e9a687-7a6a-45bd-a200-b7f4852201e1.png)
- Another thought that is worth investigating is the complexity of the form and is there is a timing issue present. This issue, like I stated earlier, does not happen on a simpler form (EX: Change Request).
- **It is worth noting that a workaround was performed in the customer's environment where we manually added the JSON rendition to a JSON that we knew worked. Once we did that the issue was resolved. This can further support the argument that something is going wrong with how the JSON is being formatted/transformed when a publish happens on the form.**

**Comment by gsteimer** [comment]
Note - more evaluation is needed to see if this is happening only for certain forms, or if it's a certain feature within the form that triggers the error.  When we tested the `Change Request` form in the PnP accelerator back in February, it didn't run into this issue.

**Comment by engerernoah** [comment]
Fix with OC Revision: 26988
XML TO JSON, REPLACE EMPTY STRINGS WITH EMPTY OBJECTS - We updated the version of the JSON jar we pull in since newer versions of ACS use updated JSON jars, however with the newer jars the xml to json conversion was updated. Previously empty XML tags were set to empty JSONObjects in the converted JSON, however in newer versions the empty XML tags were set to empty strings in the converted JSON. We had a few places in our code that expected empty JSONObjects and thus had some failures. Linked below are two github issues that were the result of the new jar using empty strings. To fix this we created a util function in the JSONUtil to convert empty strings to empty objects, we don't want to do this for every empty string in the JSON however as there could be empty attributes such as name or type that came from the XML. Therefore, we set up a whitelist of XML tag names to convert from empty string to empty object in the wizard config. The whitelist can be found in the wizard-defaults.properties file and is accessed through a getter in the wizard config. Any area in the wizard code calling the XML to JSON method now calls the util function immediately after with the whitelist from the wizard config. 
CR aking, skovacinski

**Comment by engerernoah** [comment]
Reopening, needs fix to be compatible across json jars

**Comment by engerernoah** [comment]
Updated OC Revision for compatibility across JSON jars - 26999
JSONUTIL UPDATING JSON ITERATION TO WORK WITH ALL JARS - Needed to update the json iteration process to support older json jars utilized in older alfresco versions. We cannot use the keySet function across all jars switching to keys iterator.

CR: aking, skovacinski
