### ISSUE TITLE
Upgrade Outdated Jackson Libraries

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2460]
See MNT: https://alfresco.atlassian.net/browse/MNT-22701

The MNT refers to AEV, but it looks like the OC amp for both ACA accelerators as well as AEV have this same issue.  We will need to update and test this for both ACA as well as AEV. 

For Alfresco versions that do include Jackson, we should be using the provided jar rather than including them in the OC amp.

**Comment by engerernoah** [comment]
UPGRADEING OUTDATED JACKSON LIBRARIES: 
OC REVISION: 27056
OA REVISION: 7472
 Ensuring that the oc amp for alfresco does not include jackson dependencies since Alfresco already supplies them. Additionally updating our jackson dependencies to match those found in alfresco version 7.1.0. Also updating the OA build to have the updated jackson version. 

CR: skovacinski, aking
