### ISSUE TITLE
Bulk Upload - allow user to navigate to individual document from bulk properties page

### ISSUE THREAD

**Issue by jrubins** [tsgrp/hpi#302]
Currently from the bulk properties page you are unable to navigate to a document from the 'status bar'; you first have to click 'Next' and then you can use the 'status bar' to navigate. We should either allow the user to navigate to a document using the 'status bar' while on the bulk properties page, or we should make the mouse not a pointer when hovering over the names of documents in the 'status bar'.

![bulk_upload_navigation_allow_click_bulk_properties](https://cloud.githubusercontent.com/assets/971647/3272450/23937eac-f318-11e3-8c5b-1d1b893eab8f.gif)

**Comment by m-brouillette** [comment]
Fixed in both BulkUpload & BulkProperties.  In both cases nextPressed is triggered with an the index to goto, so that the subviews build correctly when we click on a breadcrumb from the bulkEdit page.  In bulkUpload, the breadcrumbs are still disabled until an object-type is selected.

HPI REV - 11637
CR - JRubins
