### ISSUE TITLE
Cascading Picklists filter on more than one attribute

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#318]
Currently, when we query for a cascading picklist, only the attribute set in the OTC as what it 'cascades from' is passed to OC. It would be nice to instead pass through all props, so we could do a filter on two or more other values without having to set-up listeners  to all those properties (which also isn't currently something you can do).

The scenario would be that Prop C depends on Prop A and Prop B, but we only want to retrieve values when Prop B is changed. This is something George is currently encountering with a demo he is setting up. It would be a relatively easy change, involving both some HPI and OC changes to get working properly.

**Comment by b-k-white** [comment]
Updated cascading picklists so that now a picklist can use values from two others. All filled out values on a form are now sent to OC, and so anything filled out may not be used to query with for other controls. Also fixed the problem where enabled picklists still stayed grayed out.(503) Unit test to go along with this change.

CR - ZK
HPI - 11791
