### ISSUE TITLE
Caching the one OTC to rule them all

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#355]
Currently in context.js:

````javascript

getAdminTypeConfig : function(objectType, callback) {
				_findOrCreateConfig(OTC.Model, adminOTCName).fetch({
					success: function(model) { 
						var shallowTypeConfig = model.get("configs").findWhere({ocName : objectType});
						if(shallowTypeConfig){
							shallowTypeConfig.fetch().done(callback);
						}else{
							app.log.warn("No type configured on admin trac for: " + objectType);
						}
					}
				});
			},
````

We don't cache any of the types a user is fetching for. For example, if the otc has Document, Folder, and HPINote, we should be lazily loading these configs into memory as they're needed.

Here's a concept:

````javascript
otc: [
    documentDeferred : $.Deferred()  --> documentConfig is loaded,

    folderDeferred : $.Deferred()  --> folderConfig is loaded,

    hpiNoteDeferred : $.Deferred() --> hpiNoteConfig is loaded
]
````

this array of deferreds loads each config into memory without killing it, such as an insurance company's very large configs, we wouldn't want to load those in all at once unnecessarily.

A poc of this concept is now in oc.js with issue https://github.com/tsgrp/hpi/issues/344

**Comment by gsteimer** [comment]
@joehof - is your approach using Local Storage better?

**Comment by joehof** [comment]
I think so - localStorage limits each item in it's map to 5MB, which I don't ever see us hitting. From there, we use that map to get either the whole OTC, or just one type config.

**Comment by joehof** [comment]
Since we only have one OTC now, we should cache is so we don't have to call out to OC for the ObjectTypeConfig whenever we need it. (a big example would be when we call the label service a lot of times in a row, like when searching or looking at Collections) We now use the browser's localStorage map to store the OTC, and context.js will check for the config in the OTC before it tries to fetch anything from OC. Logging out will clear the config from localStorage.

Added with revision 11519
