### ISSUE TITLE
Firefox - Search Results Controls and Dates not displaying properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#511]
See the screenshots below.  On Firefox, the search controls are not aligned properly and dates are shown as "NaN".  Both work properly on Chrome and IE.

![image](https://cloud.githubusercontent.com/assets/1377228/5480646/c80c9508-860d-11e4-88fc-e5a4f80d8484.png)

![image](https://cloud.githubusercontent.com/assets/1377228/5480651/d86f8fb8-860d-11e4-8f59-aaa75b4f3da5.png)

**Comment by eric-gottschalk** [comment]
Commit #11464
Changed column sizing from md to lg and xs. Added xs so IE8 would format correctly because of its smaller screen size. Added form-horizontal class to the knock out code that creates the label for the filter so the label and filter appear inline. 
CR: Jason

![chromesearchtoolbar](https://cloud.githubusercontent.com/assets/8784120/5668433/054704de-9735-11e4-8d6d-f394d875aef5.png)
Appearance in Chrome. 

![ie8searchtoolbar](https://cloud.githubusercontent.com/assets/8784120/5668414/d7d66602-9734-11e4-8875-9e9789c646f0.png)
Appearance in IE8
