### ISSUE TITLE
Saved Search Dashlet - Consistent pagination controls look and feel

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#517]
See below.  The pagination controls for saved search dashlets should look more like the search pagination controls:

**Saved Search**
![image](https://cloud.githubusercontent.com/assets/1377228/5631082/3f844fd8-9589-11e4-82d7-b590b8645221.png)

**Search Results**
![image](https://cloud.githubusercontent.com/assets/1377228/5631084/4d9d54b6-9589-11e4-84eb-79cb7ad71c8e.png)

The only difference should be that the saved search controls shouldn't have the Check All / Uncheck All button

**Comment by eric-gottschalk** [comment]
Commit #11463
Changed the class that contains everything in a row from form-inline to form-horizontal. Added bootstrap column sizing classes, including col-xs so IE8 would format correctly because of its smaller screen size. Added a label for the filter input when a browser is in IE8 using knock out.    
CR: Jason

![chromesavedsearch](https://cloud.githubusercontent.com/assets/8784120/5668052/27a0211c-9732-11e4-8db7-4ed1aec0bcfe.png)
Appearance in Chrome

![ie8savedsearch](https://cloud.githubusercontent.com/assets/8784120/5668060/3666947e-9732-11e4-9274-9f811effa0dc.png)
Appearance in IE8
