### ISSUE TITLE
Stage - Extra space on the right side

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#519]
See the screenshot below - there's a bit of extra wasted space on the right side of the stage:

**Viewing Document**
![image](https://cloud.githubusercontent.com/assets/1377228/5631228/7da91496-958a-11e4-9bad-a7ea14dd5a47.png)

**Viewing Action - Folder Notes**
![image](https://cloud.githubusercontent.com/assets/1377228/5631214/5cf427d6-958a-11e4-88ab-b52b99cc3c64.png)

**Viewing Action -- Bulk Upload**
![image](https://cloud.githubusercontent.com/assets/1377228/5631220/68ead0ee-958a-11e4-8d26-1e9d9c43d153.png)

I believe @mbowen000 had some ideas on what we need to do to get rid of the extra space...

**Comment by joehof** [comment]
![extraspaceissue](https://cloud.githubusercontent.com/assets/4852255/5928431/d929549a-a640-11e4-85bf-760267f4a2bf.gif)

Looks like this could be an issue with webkit styling on the right bar div. It seems to be shrinking the div a bit for whatever reason.

**Comment by jrubins** [comment]
This only happens when you interact with something in the stage and it causes the `toggleLeftBar` event to get triggered. The stage has a listener for the `toggleLeftBar` event that adjusts the classes on the `leftBar` and `rightBar` DOM elements (those are the DOM elements' IDs). What we do is add the bootstrap `col-md-3` class to the `leftBar` and `col-md-9` class to the `rightBar`. This causes the extra `15px` of padding on the right pane - you can actually see the extra space on the left and ride side of the right pane . If you refresh the page this extra padding is not there because the `toggleLeftBar` event has not yet been thrown and we don't use the Bootstrap `col-md-*` classes in our HTML (we only apply them dynamically). This is really a side effect of us messing with the `margin` of any `.stage-container .row` elements.

**Comment by joehof** [comment]
This turned out to be a two part problem. First, as mentioned above, we start switching classes when "toggleLeftBar" listener in stage.js was fired, and this would add padding based on the bootstrap classes. Second, the full-pan class was having a %97 width added to it by its stylus sheet. Best guess is that this was added before the upgrade because we were doing stuff wrong back then, and now we don't need it since bootstrap is used correctly.

Fixed with HPI build #11798
