### ISSUE TITLE
Annotation indicator in stage is not displaying properly when doc viewer not set to stream annotations

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#544]
See the screencam below.  When the docviewer is configured to *not* stream the annotated version:

![image](https://cloud.githubusercontent.com/assets/1377228/5838433/173c0faa-a14d-11e4-9e51-4209dd76f5a3.png)

The annotation indicator in the stage says that the document is not annotated, even when it is:

![image](https://cloud.githubusercontent.com/assets/1377228/5838448/2c530c2c-a14d-11e4-90ca-ba2f0e977104.png)

The icon behaves properly when the doc viewer config is set to stream the annotated version.

![annotation-indicator](https://cloud.githubusercontent.com/assets/1377228/5838475/58d89316-a14d-11e4-9798-c6893e43b22c.gif)

@eric-gottschalk - could this be related to #536 that you just fixed?

**Comment by eric-gottschalk** [comment]
Commit #11563
docviewer.js
Moved the call to get the document annotation out of an if statement so it always executes. The observable isAnnotated stores whether the document is annotated. Changed the value the view returns from isAnnotated to showAnnotations. showAnnotations now returns the value of a check to see if the config allows annotations and the document has annotations.  

docviewerSpec.js
Added callback value to unit tests that are initializing a view that used to have a blank spy on the call to get the document annotation because the view is rendered in the callback. The last three unit tests now check the child view of docView to get the value of showAnnotations. 

legacyPdfViewer.js
Changed isAnnotated to showAnnotations

pdfViewer.js
Changed isAnnotated to showAnnotations

CR: Jon Rubins
