### ISSUE TITLE
Bulk upload filename tooltips not showing

### ISSUE THREAD

**Issue by jrubins** [tsgrp/hpi#545]
There used to be tooltips for Bulk Upload for filenames that were long. These are no longer showing when you hover over a long filename in Bulk Upload. The code is still in the JS file but something is off.

![bulkupload_tooltips_missing](https://cloud.githubusercontent.com/assets/971647/5840597/47918cfc-a15c-11e4-8a7b-51091fa2d27f.gif)

**Comment by m-brouillette** [comment]
When support for image thumbnails was added, the "acceptedDocs" were changed from labels to div's.  Because of this change, the jQuery which was used to append on the tooltips wasn't finding the acceptedDocs, since it was looking for labels.

Also improved the tooltips to be larger for exceptionally large filenames.

HPI REV - 11619
CR - ZK
