### ISSUE TITLE
Types not used in trac - filter not working

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#549]
See the screencam below.  The filter for the "Types not used in Trac" toss across in Trac Admin isn't filtering at all:

![admin-filter](https://cloud.githubusercontent.com/assets/1377228/5861331/ed88002e-a22d-11e4-870e-8082a213707f.gif)

**Comment by eric-gottschalk** [comment]
Commit #11596
tracconfig.js
Added checks to see if the view has already been rendered so it is not re-rendered in the deferred that creates the toss across layout and in the before render. Moved the bind in the deferred that creates the toss across layout to be at the start of the .done function instead of in the callback. 

CR: Mike Blum
