### ISSUE TITLE
Types used in trac - types do not save

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#550]
See the screencam below.  It's impossible to save the types used in trac toss across:

![types-used-in-trac-fail](https://cloud.githubusercontent.com/assets/1377228/5861385/666e5678-a22e-11e4-88a0-2dae78e5c3c1.gif)

Seen on edge2 using the Engineering Sales trac.

**Comment by eric-gottschalk** [comment]
Commit #11596
tracconfig.js
Added checks to see if the view has already been rendered so it is not re-rendered in the deferred that creates the toss across layout and in the before render. Moved the bind in the deferred that creates the toss across layout to be at the start of the .done function instead of in the callback. 

CR: Mike Blum
