### ISSUE TITLE
Stage Info has two save buttons

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#559]
![image](https://cloud.githubusercontent.com/assets/4852302/5940986/cb90785c-a6d3-11e4-8b56-1ec2d55fc9be.png)

At first I thought the config wasn't saving the label properly, but it's because I didn't click the "Save Stage Info Config" button first. Everything should save with the default "Save Config" button

**Comment by gsteimer** [comment]
@joehof - correct me if I'm wrong, but I believe this was because you were trying to do stuff in all backbone when there was also some knockout going on.  This has always annoyed me, and I'm betting that getting this into a client estimate will be tough.  Let's see if we can fix it in the next HPI release...

**Comment by grahamsinger** [comment]
Fixed with revision #12492

In stageconfig.js we were creating a new stageInfoConfig model instead of using the existing one which was causing weird saving issues.  Now just clicking the normal 'Save Config' button does all the work.

CR: Zaq

**Comment by cmlewis** [comment]
Reopening. Updating of Stage Info label does not persist now that the second button has been removed.

**Comment by grahamsinger** [comment]
Fixed with revision 12748

Models attributes weren't ever being saved (obviously).  So, I added an event to do that.

CR: ZK
