### ISSUE TITLE
Facets on Alfresco 5 - clicking one box clicks all the boxes in the same group

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#575]
Facets are broken again for some reason. Clicking one box selects all the others in the same group, rendering facets useless.

![image](https://cloud.githubusercontent.com/assets/4852302/6151976/354ff590-b1df-11e4-9e93-8d5dbfdde6d2.png)

Tagging @b-k-white @m-brouillette  - Marc, I heard you fixed this once already. Any ideas?

**Comment by m-brouillette** [comment]
When I fixed this for Gridview originally, it actually got fixed as side-effect of a different fix related to gridview pagination w/facets.  All I did for that was, have it navigate to the correct page and call fetch() on the query.

Looking at Trunk now it seems my changes were overwritten by @b-k-white 's new work with facets.

**Comment by cmlewis** [comment]
@m-brouillette Thanks for the update. Do you think this would take long to fix?

**Comment by jrubins** [comment]
Looks like in `AbstractAlfrescoEmbQueryImpl#executeQuery` trunk is currently using `org.alfresco.service.cmr.search.SearchParameters` when it used to use `TSGSearchParameters`. This is bad because our custom code in `TSGSolrQueryHttpClient` to filter the search using selected facet values first checks if the search parameters of the query are an instance of `TSGSearchParameters` before actually limiting the query.

For reference, this change happened in the `alfresco-fts` feature branch of OC in revision #10304.
@benallenallen @ladams13 Was there a reason for changing this type?

To fix this, I'm changing the search parameters object class back to `TSGSearchParameters` so we can add our facet query values and have it filter properly.

Also of note, this setting of filter queries and using the `TSGSearchParameters` should be removed from `AbstractAlfrescoEmbQueryImpl` once we can confirm the proper functionality of faceting in Alfresco 5.

**Comment by jrubins** [comment]
Fixed in OC Revision #10851 for Alfresco 4.

Waiting to close issue for @cmlewis to have a chance to confirm faceting on Alfresco 5.

**Comment by cmlewis** [comment]
This is not currently working in Alfresco 5 because we need to create the proper overlays with TSGSolrQueryHttpClient (not because the code is wrong necessarily). The Alfresco 5 builds are turning into a bit of a nightmare with certain jars not being available in Alfresco maven (surprise!) and other classes being moved or deleted that OC includes.

I confirmed this is working on edge2 / 4.2.1, so we could close this issue and either create a new one or just put it on the list of things to test on Alfresco 5 once the build is fixed. @gsteimer Thoughts?

**Comment by gsteimer** [comment]
Let's keep this issue open so we have the history.  I'll move the milestone to 2.4 since we're not going to be using Alfresco 5 on release2.

**Comment by joehof** [comment]
Fixed with HPI revision #12737 and OC revision 12113.

The checkbox problem was due to the check/uncheck logic being in a standalone ko.computed() which was run logic when it didn't need to be.

The overlay problem is now fixed based on the way we handle facets. Now we create a new property search parameter whenever we have a facet, instead of building up a filterQuery which we then read in the TSGSolrQueryHttpClient class. This may mean we can do away with the TSGSearchParameters object all together.
