### ISSUE TITLE
"Why can't I" action enhancement

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/hpi#604]
The action framework automatically filters out actions that a user may not perform based on the permissions of the user, the document, etc. However, users do not see WHY they cannot perform a given action. This can be frustrating and unclear for users to not be able to understand why they can't complete a workflow task, or annotate a document, or whatever action they are incapable of performing.

This enhancement would allow a user to have some visibility to why they can't perform a certain action at a given time. From a high level, design would include at least these checkpoints:

- Setting a user-friendly message in conditions explaining why a condition failed whenever a condition returns false (OpenContent ConditionEvaluators)
- Adding an ability to the HPI Admin action config to not show an action with the "why can't i..." feature (we want the admin to have a choice what actions to have show up here and what not)
- Adding capability to each location where actions can be consumed (header, folder actions, doc actions, search group actions, right click actions, etc), or at least a considered approach where to implement this and where not to implement this

Talk to me before designing/starting on this. @joehof may also be interested.

**Comment by gsteimer** [comment]
@joehof @dgrumieaux - one thing to watch out for is the groupedConditionEvaluatorList.  A few Active Wizard actions use it.  I've noticed that these don't show up in the HPI admin in the admin action config...

**Comment by b-k-white** [comment]
A possible solution to this problem would be to have an HPI admin toggle to show a given action if its conditions are not passing. The folder action bar, or docviewer action button, could show as disabled(greyed-out), and when the user hovers over the action, a popover could appear and explain why that action isn't available. 

This way, an action like Complete Approval Workflow, could show as disabled if the user hasn't created pdf renditions for workflow documents(and then the user easily learns what they should do to enable the action), but something like Change Form Owner could be configured to never show as disabled, because if the current user isn't the owner, there is no point in showing them this disabled action because there isn't anything they could edit/fix to enable this action.

**Comment by gsteimer** [comment]
The gray-out option should only be added upon client request.  I can see clients wanting most actions to be invisible when not available, so the separate "why can't I" action makes the most sense.

The case @b-k-white mentions above does make sense, but only when the form is in a workflow and you're the person that has the task.  Otherwise, the user shouldn't see the Complete Task action (user doesn't have the task, the form is in Draft or Approved, etc) and won't care why the action isn't appearing.

**Comment by b-k-white** [comment]
@gsteimer  True, if my approach were used, it might be necessary to have additional sliders in the action's config to decide which condition failures should cause the action to show as disabled. That way the action only shows as disabled when the user could do something to fix the problem and enable it.

**Comment by gsteimer** [comment]
@joehof - can this one be closed?

**Comment by gsteimer** [comment]
This doesn't seem to be working properly on edge2.  On the Controlled Docs trac, I have the Checkout action setup as the only "Why Can't I" action.  

For a doc that I cannot checkout, I see two "Why Can't I" actions.  One correctly shows the reason why I cannot checkout the doc, the other shows nothing.

![why-cant-i-edge2-cant](https://cloud.githubusercontent.com/assets/1377228/7823124/1d05c0c8-03bf-11e5-839a-33aa82e84a8d.gif)

For a doc that I *can* check out, I only see the 'bad' one:

![image](https://cloud.githubusercontent.com/assets/1377228/7823179/589b7876-03bf-11e5-9d81-cf525e89591e.png)

![image](https://cloud.githubusercontent.com/assets/1377228/7823186/5dbea918-03bf-11e5-88dd-6ff04e1a442f.png)

**Comment by joehof** [comment]
The "Why Can't I" action would sit on the actionCollection in memory if it was ever added, so the next time Stage was hit, a second action would appear. The easiest solution turned out to be removing the "Why Can't I" action (if it existed) at the beginning of the filterAction() function in action.js. It would get re-added later on in the function if it needed to be.

Fixed with HPI revision 12537
