### ISSUE TITLE
Two timezones displayed in date time view

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#611]
When the HPI admin is setup to display dates like this:

![image](https://cloud.githubusercontent.com/assets/1377228/6640121/5620a3e6-c963-11e4-9f23-7a75aa48955f.png)

Then date/time values end up displaying like this:

![image](https://cloud.githubusercontent.com/assets/1377228/6640143/6928cf0e-c963-11e4-996b-87f2737a44bb.png)

From talking to @joehof it sounds like this is because the code is simply doing two transformations and concatenating them together.

A better solution would be to only execute one transformation.  The actual format used for the date time should be something like:

`MM-DD-YYYY hh:mm A z`

And then dates would use:

`MM-DD-YYYY z`

**Comment by grahamsinger** [comment]
Fixed with revision #12462

Made sure that when a "Date-Time" is formatted, two time zones are not shown to the user if both the date and time are configured to display it.  The time zone will still show for both date and time individually (if configured to do so).

Fixed in both context.js and formsupport.js as formsupport doesn't use context to do its formatting.

CR: Joe Hof
