### ISSUE TITLE
View Versions - version labels sorted alpha instead of numerically

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#621]
We need to sort versions numerically instead of alphabetically:

![image](https://cloud.githubusercontent.com/assets/4852302/6714664/82a27f40-cd67-11e4-8b2c-93c436d590d1.png)

**Comment by gsteimer** [comment]
Note - in Documentum, version labels will look something like this:

`1.5, CURRENT, LATEST`

We'll either need to sort on the backend by date, or some sort of integer value on the front end and sort on the value (with the existing display value)

**Comment by jrubins** [comment]
We actually already had the `creationDate` of each verrsion available to us client side. This update just changed our sorting from the version label name to the creation date of the version.

HPI Revision #11989.

**Comment by cmlewis** [comment]
Updated to sort descending by creation date. We want the latest version displayed at the top.

HPI rev 11995.

**Comment by jrubins** [comment]
Issue with the sorting had to do with the fact that the `creationDate` in Alfresco was the same value for each version that came back from OC. So the sorting on the `creationDate` didn't actually sort properly and the versions were just displayed in the order they came back from OC.

This is fixed with HPI Revision #12015. Now were are sorting our versions based on their `modifiedDate` properties, which is consistently correct for Alfresco and Documentum.

**Comment by jrubins** [comment]
Looks like some versions can have the exact same modified date. In this case, we'll need to sort on the version label.

**Comment by jrubins** [comment]
The sorting for view versions was still off because some versions in Alfresco were coming back with the EXACT same `modifiedDate` attribute value. Therefore, we need to go back to sorting on the version label. 

However, our previous method of sorting on the version label was incorrect because it was doing a pure number sort. In a pure number sort, 1.10 is less than 1.8 and would therefore come before 1.8. But in a version sort, 1.10 is greater than 1.8 (since the "10" part is greater than the "8" part after the period) and therefore comes after 1.8.

HPI Revision #12017.
