### ISSUE TITLE
View Versions - add date created column

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#622]
In HPI 1.x, the View Versions action displayed the version label and the date created and no comment. It would be useful to display all three columns in the new HPI.

When this gets added and if it's possible, we can sort the versions by this date, which will correct the version label sorting issue here: https://github.com/tsgrp/hpi/issues/621

**Comment by jrubins** [comment]
Added "Date Created" column for versions.

HPI Revision #11989.

**Comment by cmlewis** [comment]
The Date Created column appears to be displaying the date the original document was created, instead of the date the version was created. I created the 3.1 version today, (4/6/15).

![image](https://cloud.githubusercontent.com/assets/4852302/7010574/deece4e8-dc67-11e4-8a6a-c5081ba82e0d.png)

**Comment by cmlewis** [comment]
Update via @jrubins - Alfresco and DCTM have different behaviors. DCTM dates are displaying properly, but in reverse order (1.0 at the top), and Alfresco displays in proper order, but not with the proper creation dates.

**Comment by jrubins** [comment]
Unfortunately, the `creationDate` property for versions in Alfresco is the same for every version... and it happens to be the creation date of the original document. It's not immediately obvious why that is the case. It could be because the versions in Alfresco are not their own objects (even though they are their own nodes). It could be due to the way we deal with creating versions in OC, that we have an `AlfrescoEmbUtil#updateVersionHistory` method that does something with the versions of an object and our knowledge about the exact functionality of this method is incomplete.

Regardless, we're now displaying a "Date Modified" column instead of "Date Created", since the `modifiedDate` property for versions comes back correct for Alfresco and Documentum.

HPI Revision #12015.
