### ISSUE TITLE
Setting Dates in HPI - Timezone Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#628]
See the screencam below.  I have my local machine in **UTC** time and HPI configured to for **America/Chicago** time.  However, when I set a date, it does not set in Chicago time, it converts from UTC to Chicago, messing up the date field:

![set-date-timezone-issue](https://cloud.githubusercontent.com/assets/1377228/6784204/530655f2-d14c-11e4-8e54-fa8f40e7eab5.gif)

We need to fix this for:

- [x] Form Support (screencapture above)
- [x] Send Notification due date (tested and works on edge2)
- [x] Set Controlled Doc effective date - tested and fails on edge2 (See below)
- [ ] Set Obsolete Date - I'm guessing this fails, given effective date doesn't work

Set effective date:
![image](https://cloud.githubusercontent.com/assets/1377228/6784241/9b3013d6-d14c-11e4-8060-62c46d86b834.png)

View Properties - this is odd to me.  This should be the 31st at midnight.  Given that my machine is in UTC, it's odd that it's only going back 1 hour and not 6.
![image](https://cloud.githubusercontent.com/assets/1377228/6784255/ae7da250-d14c-11e4-96b8-de65c2601607.png)

This is odd too - if I go to set the effective date again, it lists the date correctly as the 31st:
![image](https://cloud.githubusercontent.com/assets/1377228/6784266/c02859fa-d14c-11e4-824b-c15b2c3b7e8c.png)

Based on the case above - I wonder if this is more of a display issue vs. the date actually being set incorrectly in the repository.

**Comment by gsteimer** [comment]
Whoever works on this should talk to @joehof before implementing a fix.

**Comment by joehof** [comment]
So this looks like the timezone.utcOffset is 300 - which makes sense due to daylight savings time. However, a straight moment().toDate().getTime() returns a time that is non-daylight savings adjusted. I will dig into the moment code to see if we can do anything about this.

**Comment by gsteimer** [comment]
Hmm... interesting.  One thing I've learned from demoing with a client in London is that England isn't on Daylight Savings Time yet, but we are.  I think they're springing forward in a week or so.  Could it be that Moment isn't correctly handling the case of different countries going into DST on different dates?

**Comment by joehof** [comment]
TIMEZONE - So it turns out daylight savings time was feeling left out with all the new timezone work. Moment can account for daylight savings time, but when we were computing our offset, we were simply calling moment() and not moment("dateString") - so moment would always assume it was dealing whatever the current clock had (standard/daylight). Thus anytime we set a day that was NOT within the computer's understanding of zone, we were coming up an hour off. Anytime we convert using moment.tz we now provide the date to moment so it can detect whether the date falls in standard or daylight time.

HPI revision #11925

**Comment by joehof** [comment]
Also - that's exactly it George. Basically, when your clock was in London time on your comp, moment was creating everything in "standard" time, since they haven't hit daylight savings. When we then try and make that date appear correctly in any timezone where daylight is already in effect, we come up an hour off.
