### ISSUE TITLE
Delete Attribute Icon in OTC Does Nothing

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#650]
The [X] icon in OTC is not clickable, making it impossible to delete an attribute from HPI admin:

![image](https://cloud.githubusercontent.com/assets/1377228/7233641/c9dd02fa-e747-11e4-952b-7ea6018f518b.png)

**Comment by gsteimer** [comment]
Note - I just tried this on release and it worked fine.  Could this be due to the BB upgrade?

**Comment by b-k-white** [comment]
I looked at this briefly, since I would like to be able to use this for client work. What I found was that the knockout click binding is working, but the alert modal confirmation of whether to delete it or not is not maintaining, and so it is impossible to delete as George said.

My guess is that the click event is triggering the modal, but then the click event continues to propagate, and causes a click event outside of the modal as well, which then closes it. Tried adding event.stopPropogation() and others, but that didn't seem to solve this.

**Comment by aviking** [comment]
I have this fixed locally. Even though the alert modal was being shown after the render() call, parts of layout-manager are async and the final callback from the render call was hiding the alert modal. This is proably a result from the Backbone Layout-Manger upgrade to 0.9.5. The fix is to wait for the render() function to finish. that.render().promise().done(function(){ //show modal here});

**Comment by aviking** [comment]
Closed with HPI Commit: 12170
