### ISSUE TITLE
Acquire Workflow Task - redirects to incorrect URL once completed

### ISSUE THREAD

**Issue by cmlewis** [tsgrp/hpi#657]
If a simple workflow is assigned to a group, any user in the group can acquire the task. After acquiring a task, HPI does an improper redirect and instead of refreshing the current page, it goes to /Stage/trac/OBJECTID and gets rid of the folder id. HPI then thinks the object is a folder.

![acquire task - incorrect redirect](https://cloud.githubusercontent.com/assets/4852302/7305198/bff851dc-e9c1-11e4-936c-79dedf3df236.gif)

**Comment by aviking** [comment]
It looks like the issue was caused because the refresh trigger was on bothIds (app.trigger("stage.refresh.bothIds", self.objectId, self.objectId)), which caused the url to navigate to use the documentId as the containerId and then trigger a refresh without updating the URL to use the no containerId and only a documentId. The temporary fix is to just call a refresh on the documentId instead of bothIds. However i think we could also look into updating the code for the refresh bothIds. 

I have this fixed locally. Waiting on a Code Review.

**Comment by aviking** [comment]
Fixed with HPI commit: 12197
