### ISSUE TITLE
Icons not appearing on IE11

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#671]
For some reason the Set Effective Date icon doesn't appear on IE11:

**IE11**
![image](https://cloud.githubusercontent.com/assets/1377228/7569515/f4de11dc-f7ce-11e4-81f6-67e8c624c32e.png)

**Chrome**
![image](https://cloud.githubusercontent.com/assets/1377228/7569530/065dd1d6-f7cf-11e4-8842-d33bb7bb765b.png)

**Comment by gsteimer** [comment]
Is this like the #634 issue?

**Comment by gsteimer** [comment]
Looks like this is also happening for the Manage Workflow Documents action:

![image](https://cloud.githubusercontent.com/assets/1377228/7865896/74ef8b84-0531-11e5-9c46-c85e8a461809.png)

The above screenshot is the folder actions of a wizard form on edge2.

**Comment by grahamsinger** [comment]
After looking into this here is where I am.  I was able to recreate the issue when I ran on a tomcat server instead of a node server.  Then after poking around online, I ended up doing two things: downloading the latest bootstrap font releases and (this is the weird part) changing my IE11 'security level' (cog in top right > Internet Options > Security Tab > change slider to 'Low').

This made the glyphicons in question show up locally but still not on edge.  Not sure if this means we should update our font files in trunk, or there is something else going on.  Also, not sure what exactly committing those font files would do, so if anyone knows...

**Comment by gsteimer** [comment]
Hmm... if we have to update the glyphicons to get this to work, that's fine - but we can't mess with IE security (or any other) settings.  Most clients have their laptops locked down and we couldn't change the settings even if we wanted to.

There must be something different about these icons.  Why aren't they treated like any other glyphicon?

**Comment by dgrumieaux** [comment]
Is there some external link that is bringing those glyphicons in instead of
them being linked to locally?

**Comment by grahamsinger** [comment]
I'm not sure; haven't looked into that.  If you look here: https://github.com/twbs/bootstrap/issues/10106 there's a list of symbols, and I've confirmed that those are the ones that don't render in IE11.  

-bell
-bookmark
-briefcase
-calendar
-camera
-fire
-lock
-paperclip
-pushpin
-wrench

But, like I mentioned before, I was only able to get this to work by changing those security settings, which appears to be an impossibility for clients.

**Comment by aviking** [comment]
Fixed with HPI commit: 12463
CR: Jason, Joe
