### ISSUE TITLE
Localize HPI strings

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#674]
HPI now has localization as a language and client feature - now we need to provide it some localizations to make use of it!

This feature targets taking text that exists in in HTML or Javascript code that would make sense to translate or override for a different locale or for a different client, and factoring that code out into the l10n .json locale files.

May want to finish #673 first.

See the Localization wiki page for more information on how to accomplish this issue.

**Comment by b-k-white** [comment]
@alieblich Has done a lot of work on localizing much of HPI. Currently, UserPrefs, OTC, Dashboard,Stage, and Search have a had a lot of localization done, and these can be found in en.json or fr.json, We only support two languages as of now, and no client customization. There is likely some remaining in Stage, as we didn't support Wizard Workflows, and other actions, but many of the actions have been set up. Often times, the labels we provide in HPI, can be given a key instead of a hard-coded label, and this key will allow it to switch between languages and other potential client localizations.

**Comment by bradleywhite2014** [comment]
@dgrumieaux We have covered all of HPI at this point, correct? Should we close this enhancement?

**Comment by b-k-white** [comment]
@dgrumieaux We have covered all of HPI at this point, correct? Should we close this enhancement?

**Comment by dgrumieaux** [comment]
Yes, localization is far enough along to close this issue.
