### ISSUE TITLE
Signin Failed message does not appear when no credentials used

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#688]
This is really odd.  On edge1, if you don't put in any credentials and click the signin button, you see the sign in failed message:

![image](https://cloud.githubusercontent.com/assets/1377228/7821338/ad736dba-03b3-11e5-8b15-cfd2f689472f.png)

BUT, on edge2, the message doesn't appear at all.  The page just reloads with no message:

![signin-no-cred-edge2](https://cloud.githubusercontent.com/assets/1377228/7821365/d2df59e2-03b3-11e5-9c1e-f31f9f419ca0.gif)

**Comment by grahamsinger** [comment]
Fixed with revision 11746 in OC.

The problem here was that an exception was not being thrown for in alfresco because the result was always being set to "valid".  This caused the response to hit the success block in HPI (making the error message fail to show) but the ticket was set to the error in the stack, causing obvious problems with logging in.

For my fix, I just added a check in the createNewSession endpoint to actually throw an exception if the username field is left blank.

CR: DG
