### ISSUE TITLE
When you navigate to a collection url, the collection table doesn't show

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#691]
![collections_not_showing](https://cloud.githubusercontent.com/assets/4852355/7885365/0dd4e4c2-05e9-11e5-809f-4fc953f0b322.gif)

**Comment by grahamsinger** [comment]
After looking into this briefly yesterday, I found what I thought the full solution would be, but a new issue came up.. When navigating to the collection URL it was using the relation name "hpi:collectionItem" instead of "hpi_collection_item" which is what is used when a collection is clicked.  Changing this allowed the results to show, but something seems to be wrong with how those results are loaded. They load, but the grid view (in my case) doesn't think there are any results, so the template looks like this.

![image](https://cloud.githubusercontent.com/assets/8784597/7961992/7a15cca6-09d0-11e5-98c0-eb74a7d12a15.png)

I haven't had much time to look into this, so I'm not sure if this is an issue that is isolated to only collections, or a farther reaching issue.

**Comment by silanke** [comment]
I believe I fixed the loading issue. The problem seemed to be a race-condition issue between the "No Results" and the GridView Layout. I added an "afterRender: function()" and modified "this.results.fetch()" in the GridView.Views.Layout initialize: function() in order to be make sure that the GridView Layout renders completely. 

I still need to test around and see if this is a "farther reaching issue" but another issue within Collections involves switching between layouts (i.e. grid, list, table). If a collection is selected and displayed and a user tries to switch between layouts using the buttons on the top right of the control-outlet, the page displays only the "No Results" view without the Collection. I am not sure if this is an issue we need to fix but I'll continue to test if my fix for the loading does not break anything and look into the layout issue.

**Comment by silanke** [comment]
Fixed with HPI Revision: 12718

Fetch was not retrieving proper url for the collections in order to display collection results. Added the data needed in RelatedChildren in ocquery. Also added a fetch call in tableview if on collections page. This fixed displaying the collection results upon refresh as well as displaying results when switching between views.

CR: Zaq
