### ISSUE TITLE
Dashboard - Clicking on dashlet tab causes page to scroll up

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#697]
See the screencap below.  As long as the dashlet is at the top of the page, it's fine.  But, if you have to scroll down to see a dashlet with tabs, clicking a tab causes the page to annoyingly scroll up.

![dashboard-tab-jump](https://cloud.githubusercontent.com/assets/1377228/8186904/971247ac-1412-11e5-9054-380c33cbb26d.gif)

**Comment by silanke** [comment]
The issue here (which occurs only in workflowreportingdashlet.js) is that we remove the view of the tabcontent first which causes the page to jump up since there is nothing for the window to keep in place. 

The quick fix is to set a .promise().done(function(){...} on the this.setView(...).render() call within tabClicked. This ensures that after all actions on this view are completed (i.e. making sure that the new view is rendered completely) then perform the function below that checks to see if the dashlet is located on the bottom half of the page and if so causes the window to scroll down.

Code:
this.setView("#subdashletDiv", this.myWorkflowsView, true).render().promise().done(function(){	
    	if($("#subdashletDiv").offset().top > (0.5 * document.body.scrollHeight)) {
    		window.scrollTo(0, 0.5 * document.body.scrollHeight);
         }
   });

This issue is only found in workflowreportingdashlet since the inbox/awinbox dashlets utilize knockout bindings for their tabClicking. If we want to just throw in that quick fix since its only occurring in workflowreportingdashlet we can do that. 

The thing is if we want more uniform functionality of dashlets with/without tabs, we may want to design an abstract dashlet for more uniform functionality among the different/future dashlets but that's just a larger task that I assume isn't really a priority.

**Comment by dgrumieaux** [comment]
Have we looked into using an anchor element, or looked into how other tabbed structures in HPI avoid this problem?

**Comment by gsteimer** [comment]
Not sure when this was fixed, but it seems to no longer happen:

![dashboard-scroll](https://cloud.githubusercontent.com/assets/1377228/23970931/c185a08c-0999-11e7-9486-5fd2cb88afcf.gif)
