### ISSUE TITLE
Power Promote Updates

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#722]
There are a few updates that should be added to the Power Promote features:

1. Look and feel of the signoff page (see below).  We need to add some better styling and make it consistent with the other actions
1. In the Admin, the action should default to requiring the user to sign off.  Currently, the setting defaults to `null`.

*Power Promote signoff*
![image](https://cloud.githubusercontent.com/assets/1377228/8574477/79d71f40-255c-11e5-9d53-81433bb90958.png)

*Normal Wizard Task Signoff*
![image](https://cloud.githubusercontent.com/assets/1377228/8574502/8ecbfb50-255c-11e5-93a2-d37e6c89bcc5.png)

*Admin - no default*
![image](https://cloud.githubusercontent.com/assets/1377228/8574520/ad7fe214-255c-11e5-8bcf-2c6429e9de86.png)

**Comment by b-k-white** [comment]
In addition to these issues, because the Power Promote now has a sign off feature, the condition to check for a PDF rendition now needs to be a part of the action. Otherwise, a sign off on a non-renditioned document will fail. The condition condition-doesdocumenthavepdfrendition-conditionevaluator should be added to the wizard-action-bean-config.xml

**Comment by stinachen** [comment]
HPI revision 12674
CR: zaq keller

**Comment by stinachen** [comment]
OC revision 11998
CR: George
