### ISSUE TITLE
Collections not working on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#751]
Looks like the code is hardcoding the relationship name:

**searchRouter.js**
```Javascript
            var collectionItems = new Ocquery.RelatedChildren({
                relationName: "hpi_collection_item",
                collectionId: collectionId
            }); 
```

The code needs to pull the value from config-project.js:

```Javascript
var config = {
	'app': {
		uniqueUserName: "loginName",
		collectionRelation: "hpi:collectionItem"
	},

```

**Comment by silanke** [comment]
Fixed with HPI Revision: 12749

In searchrouter.js, relationName in collectionItems were hard-coded for Documentum. Fixed by setting the relationName attribute with app.collectionRelation which contains the correct relationName in the appropriate config-project.js whether it's Documentum or Alfresco

CR: Zaq
