### ISSUE TITLE
User Preferences saving every minute, regardless if it's changed or not

### ISSUE THREAD

**Issue by zkeller** [tsgrp/hpi#764]
See below, I've just had edge open in a tab and we are spamming with saving. This should not be happening. We need to check if it has changed since the last save before we actually save.

![userprefspam](https://cloud.githubusercontent.com/assets/4852355/8967079/72e96036-35fa-11e5-96d2-10973f68b648.png)

**Comment by dgrumieaux** [comment]
http://backbonejs.org/#Model-changed - should make this a trivial fix

**Comment by b-k-white** [comment]
Fixed locally, will get a CR to commit tomorrow

**Comment by b-k-white** [comment]
Fixed up issues with saving every minute. Also stopped it from fetching every time the getUserPreferences was called as well. It now  checks to see if it has it. It now saves with a throttle set to 1min, so that it only saves when it has been updated. Manual triggers of saves will now need to happen. Styling also fixed so that it looks good on small devices.
CR - Dan G.
HPI-12784
