### ISSUE TITLE
Table view - force fit columns incorrectly sets to false

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#786]
I'm not sure how this happens, but ever since the new user preferences changes, I randomly see the "Force Fit Columns" setting in table view set to false.  For example:

Admin default - true
![image](https://cloud.githubusercontent.com/assets/1377228/9443774/9f26a278-4a48-11e5-98e7-4904a95c8ed4.png)

After search - false:
![image](https://cloud.githubusercontent.com/assets/1377228/9443787/b9546fe0-4a48-11e5-9d1a-f78c9b58aca3.png)

I feel like I've only seen this for tracs/types that I haven't searched on yet after clearing my table view settings in user preferences.  In other words, I'm guessing that table view is _incorrectly_ setting it to false when it's relying on the admin config, but _correctly_ setting it to true after I manually click the box and it gets saved to my user prefs.

**Comment by grahamsinger** [comment]
Fixed with rev12938

If `userPrefs[queryType].isForceFit` was undefined it would default to false, instead of falling back on the config.  Now we make sure to check the config if `userPrefs[queryType].isForceFit` is undefined, while also making sure to prefer the userPrefs over the config if they do in fact exist at a later point.

CR: MB
