### ISSUE TITLE
Force Fit Columns - setting is not sticking

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#795]
@grahamsinger - did you test this?  Seems like when I set forcefit to false, it just comes back true when I search again.  Shouldn't that change be saved to the client side model right away?

![force-fit-fail](https://cloud.githubusercontent.com/assets/1377228/9498316/cb7965d0-4bde-11e5-9a2c-90a22907d698.gif)

**Comment by grahamsinger** [comment]
hmm. yeah, let me see whats up

**Comment by grahamsinger** [comment]
The issue here was that I was (attempting) to test for the existence of the forceFit attribute on the userPrefs, but if it existed and was false, it would hit the same code (which chooses whatever is in the config).  I've fixed that now, awaiting CR.

Something I was wondering when I was testing however: should the column widths toggle as you check/uncheck "Force Fit Columns"?  It seems like it does when turning force fit on, but not when turning it back off.  @gsteimer

**Comment by gsteimer** [comment]
Ideally it should toggle right away, but is that more in SlickGrid's code?  If so, I don't think we should try to hack into there.  If it's us, then, yeah - let's make it change right away.

**Comment by grahamsinger** [comment]
Fixed at rev12948

Fixed the issue I described above.  Also, removed the `grid.autosizeColumns()` call when we turn force fit off because that function does the same thing as setting `forceFitColumns` to true.  So, it would do the opposite of what it should.
