### ISSUE TITLE
Export Search Results Include All Configured Attrs

### ISSUE THREAD

**Issue by ladams13** [tsgrp/hpi#824]
The Export Results action only pulls the currently displayed attributes.  A client has requested that we add the ability to export all attributes associated with the results returned.

I also noticed while looking into this that the ocName is pulled in the Export results, our client will want the labels of the attributes displayed instead.

**Comment by gsteimer** [comment]
@ladams13 - I think this is a good update, but be careful with the labels.  The label service is only implemented on the HPI side.  OC has no knowledge of labels set in HPI.

How are you proposing that the export action (which runs in OC) will get the labels?

**Comment by gsteimer** [comment]
Also - a few other questions:

- Do you intend to include all attributes that were returned by the search (including any attributes that may not be displayed) OR, do you mean all attributes on the object (whether or not they're returned in the search)
- How are you going to handle ordering of the attributes?  I'd say to honor the order of the visible attributes in the table (which I think the existing code already does) and then append any other attributes to the end.

**Comment by m-brouillette** [comment]
I think I can chime in here as to how to accomplish this OC without it having knowledge of the labels.  For OA I wrote an ExcelUtil in 1.core, that in a fairly general fashion will generate a report based on whatever it receives from the frontend.  
That would mean we could just send it the search data from HPI, in whatever way we want it to be displayed, rather than OC having to convert from / look up labels.

**Comment by m-brouillette** [comment]
There is now a config option ExportSearchResults, that when enabled exports all Attributes configured as either Primary or Secondary Attrs on the FormConfig, which SearchConfig is configured to use.  When that option is not configured, the old behavior of exporting only fields currently visible in search is executed.

Using Labels rather than OC Names is still a work in progress, so I'll leave this issue open.

Added in HPI REV - 13476

**Comment by gsteimer** [comment]
@m-brouillette - I'm trying to set this up on edge2, but it doesn't seem to be working properly.  See below - my hidden fields contain `Status`, but that field isn't present in the excel spreadsheet:

![image](https://cloud.githubusercontent.com/assets/1377228/10739926/63efeba2-7bed-11e5-8429-dd81f076a8bf.png)

![image](https://cloud.githubusercontent.com/assets/1377228/10739935/6cdbc86c-7bed-11e5-83dc-a0ac30c76897.png)

**Comment by m-brouillette** [comment]
Is status configured on the FormConfig for the type that your exporting?  The Export Action when configured to show all fields exports all fields primary and secondary fields configured on the FormConfig, which are not necessarily the same as the union of Shown/Hidden fields on the Search Config for that type.

**Comment by gsteimer** [comment]
Are you talking about the form that's configured on the search config?

If that's the case, I don't think this is going to work for most client scenarios.  Correct me if I'm wrong, but that would mean that you can only export attributes that are on the advanced search form.

Maybe I'm missing something - how would you configure an attribute to export that isn't on the search form, but is in the results?

**Comment by m-brouillette** [comment]
We now use the visible / hidden attrs on the searchConfig rather than the formConfig.  We now also export the pretty labels to be used as the column headers.

HPI REV 13754 / OC REV 13196 CR - Zaq

**Comment by gsteimer** [comment]
@m-brouillette - on edge1, I see it correctly exporting all columns as requested, but the pretty labels are not in the spreadsheet:

![image](https://cloud.githubusercontent.com/assets/1377228/11220160/28bc6748-8d24-11e5-9f59-dac228e205e0.png)


![image](https://cloud.githubusercontent.com/assets/1377228/11220165/2fa88c44-8d24-11e5-8543-2c50d40945b0.png)

**Comment by gsteimer** [comment]
This is working now - edge1 wasn't being updated and deployed properly so it was running old code...
