### ISSUE TITLE
Review Route with more than one user removes the "completed" users once they have approved

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/hpi#840]
When running a review route with more than one user, the "View Wizard Workflow Status" action only displays the remaining reviewers, it does not show the reviewers that have already completed

![image](https://cloud.githubusercontent.com/assets/4850976/10397067/7340aa04-6e6b-11e5-85bf-50830eacf621.png)

![image](https://cloud.githubusercontent.com/assets/4850976/10397060/6aeae6bc-6e6b-11e5-8873-6c98acae85bf.png)

**Comment by dgrumieaux** [comment]
For context - this is because for the review route, this page is not generated from Approval Details (which is what it is driven by when in the Approval route). This is just showing the outstanding Activiti workflow tasks for the Review route. The fix would potentially be to make it show tasks that were already completed in addition to outstanding.

**Comment by nwoodbine** [comment]
Fixed in OC Revision 12876, HPI Revision 13461

**Comment by gsteimer** [comment]
Issues:

- [ ] Status says not in workflow when it actually is
- [ ] While in review route (or approval route), change 'Route Preview' to Route Status
- [ ] After review and approval route (complete, reject abort), clear out approval details (to keep approval and review consistent)
- [ ] Task emails and completed emails are blank (for review, test approval as well)

![image](https://cloud.githubusercontent.com/assets/1377228/10611196/8f808bd2-7710-11e5-94f0-20f1f84b7e6f.png)

**Comment by nwoodbine** [comment]
Fixed issues above in 

HPI revision 13482
OC revision 12884
