### ISSUE TITLE
Form Config Updates - Remove NONE, Special, ConfigDropdown and Multiselect control types and default fields properly

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#903]
The Form Config admin includes a number of controls that are old an no longer supported in form support.  We should remove these:

- [ ] NONE
- [ ] Special
- [ ] ConfigDropDown
- [ ] MultiSelect

Additionally, while we're in here, we should default these fields in a more user-friendly manner:

- [ ] Date and Datetime fields should default to DateBox (user can decide to change to DateTimeBox)
- [ ] All other fields should default to Textbox

@joehof @zkeller - Feel free to reply if you have other thoughts on how we should default fields.

**Comment by ZachGerth** [comment]
Fixed with revision # 13903. The old configs have been removed and the defaults are now set to Date and Datetime -> DateBox, or Textbox. If an old HPIAdmin has the formconfig set to one of the deprecated types, it will default to AutoComplete in FormConfig, but won't save until the user saves it - it will still use the old one until a new configuration is saved from the HPI Admin page.
