### ISSUE TITLE
Disable Admin Navigation in config-project.js

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#925]
This would be super helpful for Solr Portal projects that have no security in place to determine who can access the admin page. My client's upgrade to new HPI is definitely going to need this in place for prod.

**Comment by gsteimer** [comment]
@nwoodbine is this a dupe of https://github.com/tsgrp/hpi/issues/886?

**Comment by gsteimer** [comment]
Sounds like this isn't completely the same as #886 since this is for a Solr portal HPI project where there is no user authentication / security.  In this case, I think the client has two options:

1. Go forward with this update.  The downside here is that *nobody* can access the admin in production.  You'd have to leave it enabled in DEV/QA and port configs.
1. Leave the admin in (making this item moot).  The workaround would be to disable `/admin` at the webserver level.  So, disable requests to `http://hpi.myclient.com/hpi/admin`, but allow requests that don't go through the webserver / loadbalancer.  For example, `http://<hpi-server-ip>:<port>/hpi/admin` would work.  This way, an enterprising user would not only have to guess the admin route, but also the server IP address and port.

Option 2 is more flexible in that a true admin user would be able to access the HPI admin in prod.  The downside is that there's still a chance (albeit small) that an enterprising user could access the admin.

**Comment by dgrumieaux** [comment]
For most of my clients I recommend updating and testing HPI configuration
updates in TEST then copying over configurations into Production. Not sure
if we'd want to lock people into that approach or not though.

**Comment by gsteimer** [comment]
From discussion in the weekly meeting - it sounds like implementing #886 will fix this issue as well (with no need to add a new setting in config-project.js

**Comment by gsteimer** [comment]
Closing this - Now that you can lock down the admin with a username/password, I believe this should address @nwoodbine's request.
