### ISSUE TITLE
Awkward Scrolling with Large Forms in Bulk Upload

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#991]
@dgrumieaux noticed this when not using a mouse while filling out a large form that requires scrolling (as shown in the image below). Basically, in order to access the hidden parts of the form, the user must click somewhere on the modal outside of the input fields and use their arrow keys. Can we improve usability here? 

![bigform](https://cloud.githubusercontent.com/assets/8784125/12828597/716a3564-cb4b-11e5-9e42-7113059fdad5.png)

**Comment by mwojno-tsg** [comment]
This issue seems to have been resolved as a result of the continual UI improvements to the application over the years. See the following screenshots and gif below demonstrating the issue has been fixed. 

![dropdownBulkUpload](https://user-images.githubusercontent.com/54864662/92036533-ffddd880-ed35-11ea-9cb5-3713be4412aa.gif)

Initial opening of dropdown: 
![image](https://user-images.githubusercontent.com/54864662/92036588-14ba6c00-ed36-11ea-97aa-9fa66dda589f.png)

Then ability to scroll with mouse to move it down the screen: 
![image](https://user-images.githubusercontent.com/54864662/92036599-1b48e380-ed36-11ea-845c-e9f221c57ffc.png)
