### ISSUE TITLE
Dropdowns at the Bottom of Large Forms Cut-Off

### ISSUE THREAD

**Issue by nwoodbine** [tsgrp/HPI#992]
Related to [this scrolling issue](https://github.com/tsgrp/hpi/issues/991), dropdowns are hidden when at the bottom of large forms. See image below. @dgrumieaux 

![hiddendropdown](https://cloud.githubusercontent.com/assets/8784125/12828822/75b20f10-cb4c-11e5-800b-2163e41f9dd9.png)

**Comment by mwojno-tsg** [comment]
This issue seems to have been resolved as a result of the continual UI improvements to the application over the years. See the following gif below demonstrating the issue has been fixed. View properties form is showed below with a dropdown near the bottom of the screen. The screen adapts at the bottom and nothing gets cut off.

![dropdownViewProps](https://user-images.githubusercontent.com/54864662/92037711-cb6b1c00-ed37-11ea-9fa6-bd2061dd41bd.gif)
